const ASSET = '../school-comparison/assets/';
const news = [
  {id:'autumn-open',date:'2026.09.04',cat:'入試情報',title:'秋の学校説明会、予約受付を開始しました',body:'10月の学校説明会では、授業見学と在校生との座談会を行います。校内を歩きながら、青葉の一日を感じてください。'},
  {id:'library-week',date:'2026.08.28',cat:'学校生活',title:'図書館の「夜の読書週間」が始まります',body:'放課後の図書館を20時まで開放し、生徒が選んだ本の展示と朗読会を開催します。'},
  {id:'sports-day',date:'2026.08.20',cat:'行事',title:'青葉祭・体育の部を実施しました',body:'学年を越えたチームで競技に挑戦。最後まで声を掛け合う姿がグラウンドに広がりました。'},
  {id:'global-class',date:'2026.08.06',cat:'学び',title:'国際コースが地域の多言語案内を制作',body:'駅から学校までの道を、地域に暮らす方への聞き取りをもとに4言語で紹介しました。'},
  {id:'club-award',date:'2026.07.29',cat:'部活動',title:'写真部の作品が県高校文化祭に選出',body:'「まちの余白」をテーマにした12点の作品が、県高校文化祭の展示作品に選ばれました。'},
  {id:'summer-school',date:'2026.07.16',cat:'学び',title:'夏季探究ゼミで問いを深めています',body:'身近な水辺の環境を題材に、観察・インタビュー・データ整理を組み合わせた調査を進めています。'},
  {id:'uniform',date:'2026.07.03',cat:'お知らせ',title:'制服リニューアルに向けた意見交換会',body:'生徒・保護者・教職員による意見交換会を開き、動きやすさと地域性について話し合いました。'},
  {id:'health',date:'2026.06.22',cat:'お知らせ',title:'保健室から：夏の生活リズムについて',body:'暑い季節も集中して学ぶために、水分補給と睡眠のポイントを保健室だよりで紹介しています。'}
];
const clubs = [
  {name:'バスケットボール部',type:'運動部',days:'火・木・土',place:'第一体育館',body:'基礎を丁寧に積み上げ、声を出して仲間の強みを引き出すチームです。初心者も歓迎しています。'},
  {name:'サッカー部',type:'運動部',days:'月・水・金',place:'人工芝グラウンド',body:'判断の速さとフェアプレーを大切に、練習後の振り返りまでを活動にしています。'},
  {name:'バレーボール部',type:'運動部',days:'火・金・土',place:'第二体育館',body:'つなぐ力を合言葉に、学年を越えて教え合いながら練習しています。'},
  {name:'弓道部',type:'運動部',days:'月・木・土',place:'弓道場',body:'呼吸と姿勢を整え、一射ごとに自分と向き合う時間を大切にしています。'},
  {name:'吹奏楽部',type:'文化部',days:'月・水・金',place:'音楽室',body:'校内行事や地域の演奏会に向けて、音色を聴き合うアンサンブルを磨いています。'},
  {name:'写真部',type:'文化部',days:'木・土',place:'メディア工房',body:'光の変化や人の気配を見つめ、撮影から展示の企画まで自分たちで行います。'},
  {name:'科学部',type:'文化部',days:'火・木',place:'理科実験室',body:'小さな疑問を実験に変え、文化祭では来場者と一緒に楽しめる展示を作ります。'},
  {name:'文芸・放送部',type:'文化部',days:'水・金',place:'図書館ラボ',body:'文章、音声、映像を通して、青葉の日常を記録し届ける部です。'}
];
const searchable = [...news.map(n=>({title:n.title,href:'#news/'+n.id,desc:n.body})),{title:'探究コース｜問いから始まる学び',href:'#learning',desc:'探究・総合・国際の3コースと進路支援'},{title:'月影図書館｜静かに深く、世界と出会う',href:'#life',desc:'6万冊を所蔵するラーニングコモンズ'},{title:'2027年度入試・説明会',href:'#admissions',desc:'入試要項、費用、説明会の日程'},...clubs.map(c=>({title:c.name,href:'#clubs',desc:`${c.type}／${c.days}／${c.place}`}))];
const main = document.querySelector('#main');
const nav = document.querySelector('#main-nav');
const pageHead = (en,jp,copy='') => `<div class="page-hero"><div class="wrap page-title"><h1><small>${en}</small>${jp}</h1>${copy?`<p>${copy}</p>`:''}</div></div>`;
const section = (content,cls='section') => `<section class="${cls}"><div class="wrap">${content}</div></section>`;
const button = (href,label,cls='button button-dark') => `<a class="${cls}" href="${href}">${label} <span aria-hidden="true">→</span></a>`;
const img = (file,alt,cls='') => `<img class="${cls}" src="${ASSET}${file}" alt="${alt}" loading="lazy">`;
function newsRow(n){return `<div class="news-row"><time>${n.date}</time><span class="tag">${n.cat}</span><a href="#news/${n.id}">${n.title}</a><span aria-hidden="true">→</span></div>`}
function home(){return `<section class="hero"><div class="hero-media">${img('campus.jpg','水辺に面した校舎と歩く人々')}</div><div class="wrap hero-content"><p class="eyebrow">私立 青葉高等学校 / AOBA HIGH SCHOOL</p><h1><span>好きが、</span>未来をひらく。</h1><p class="hero-copy">自分の「なぜ」を持ち寄って、まだ名前のない未来へ。青葉は、学びと日常がゆるやかにつながる学校です。</p><div class="hero-actions">${button('#about','青葉を知る','button button-light')}${button('#admissions','説明会を見る','button button-outline-light')}</div></div></section><div class="notice-strip"><div class="wrap notice-grid"><b>重要なお知らせ</b><div class="notice-item"><time>2026.09.04</time><span>秋の学校説明会、予約受付を開始しました</span></div><a class="text-link" href="#news/autumn-open">詳細</a></div></div>${section(`<div class="section-head"><div><p class="eyebrow">WALK THROUGH AOBA</p><h2>写真で見る、<br>青葉の一日。</h2></div><p>朝の光が差し込む教室、放課後の体育館、誰かの問いが残る図書館。学校の空気を写真から感じてください。</p></div><div class="photo-grid"><a class="photo-tile" href="#life">${img('students.jpg','校舎のそばで過ごす生徒たち')}<span class="photo-label">学校生活・施設</span></a><a class="photo-tile" href="#learning">${img('classroom.jpg','教室で学ぶ生徒たち')}<span class="photo-label">学び</span></a><a class="photo-tile" href="#life">${img('library.jpg','本棚のある図書館')}<span class="photo-label">図書館</span></a><a class="photo-tile" href="#clubs">${img('basketball.jpg','体育館のバスケットボールコート')}<span class="photo-label">部活動</span></a></div>`)}${section(`<div class="section-head"><div><p class="eyebrow">NEXT STEP</p><h2>知りたいことから、<br>見つけよう。</h2></div><p>学校選びの今に必要な情報へ、迷わず進めるように。気になる入口を選んでください。</p></div><div class="feature-grid"><article class="feature"><h3>学びの輪郭</h3><p>3つのコースと探究授業、進路支援について紹介します。</p>${button('#learning','学びを見る','text-link')}</article><article class="feature"><h3>日常の手触り</h3><p>1日の流れ、行事、施設、部活動。生徒の時間を覗いてみませんか。</p>${button('#life','学校生活を見る','text-link')}</article><article class="feature"><h3>会いに行く</h3><p>授業見学と座談会で、青葉の人と場所を体験できます。</p>${button('#admissions','説明会を選ぶ','text-link')}</article></div>`,'section section-tint')}${section(`<div class="section-head"><div><p class="eyebrow">LATEST NEWS</p><h2>お知らせ</h2></div>${button('#news','一覧を見る','text-link')}</div><div class="news-list">${news.slice(0,4).map(newsRow).join('')}</div>`)}${section(`<div class="split"><div><p class="eyebrow">MESSAGE</p><h2 class="quote">問いを持つ人は、<br>どこへでも歩いていける。</h2></div><div class="prose"><p>青葉高等学校は、1968年に小さな私塾として始まりました。知識を手渡すだけでなく、自分の目で見て、考え、誰かとつくる学びを大切にしています。</p>${button('#about','学校紹介へ','text-link')}</div></div>`)} `}
function about(){return `${pageHead('ABOUT AOBA','学校紹介','ここで過ごす時間が、あなたの問いを育てる。青葉の考え方と歩みをご紹介します。')}${section(`<div class="split"><div><p class="eyebrow">EDUCATIONAL PHILOSOPHY</p><h2 class="quote">好きという小さな灯りを、<br>学びの起点に。</h2></div><div class="prose"><p class="lead">青葉では、一人ひとりの興味を「寄り道」ではなく、未来へ向かう入口だと考えています。</p><p>正解を早く当てることだけを目標にせず、問いを立て、仲間と試し、言葉にして伝える。教科の学びも、行事も、地域との出会いも、そのためにあります。</p><p>違う得意を持つ人が同じ場所で過ごすからこそ、見える景色が増えていく。安心して挑戦できる余白を、学校の中につくります。</p></div></div>`)}${section(`<div class="split"><div class="prose"><p class="eyebrow">MESSAGE FROM PRINCIPAL</p><h2>校長挨拶</h2><p class="lead">「やってみたい」を、<br>誰かと育てる学校へ。</p><p>校長・水野 朔です。高校時代の私は、放課後の図書館で出会った一冊から、まちの水辺を調べ始めました。ひとつの関心が、人と地域をつなぎ、学ぶ理由になった経験です。</p><p>青葉の教職員は、生徒の隣で答えを急がずに考えます。小さな好奇心を歓迎し、失敗を次の仮説に変える。そんな毎日を一緒につくっていきましょう。</p><p><b>校長　水野 朔</b></p></div>${img('students.jpg','校舎の中庭で話す生徒たち')}</div>`)}${section(`<div class="section-head"><div><p class="eyebrow">HISTORY</p><h2>青葉の歩み</h2></div><p>地域とともに学ぶ学校として、時代に合わせて学びの場を更新してきました。</p></div><div class="timeline"><div class="timeline-item"><time>1968</time><p>青葉学習塾として創立。地域の子どもたちに開かれた学びの場が始まる。</p></div><div class="timeline-item"><time>1984</time><p>青葉高等学校を設置。共学の普通科として新たな一歩を踏み出す。</p></div><div class="timeline-item"><time>2008</time><p>総合学習を再編し、地域連携型の探究プログラムを開始。</p></div><div class="timeline-item"><time>2018</time><p>創立50周年。図書館ラボとメディア工房を整備。</p></div><div class="timeline-item"><time>2024</time><p>探究・総合・国際の3コース制へ。選択と対話を軸にした学びを拡充。</p></div></div>`,'section section-tint')}${section(`<div class="section-head"><div><p class="eyebrow">AT A GLANCE</p><h2>学校概要</h2></div></div><dl class="rule-list"><div><dt>学校名</dt><dd>私立 青葉高等学校</dd></div><div><dt>創立</dt><dd>1968年（昭和43年）</dd></div><div><dt>所在地</dt><dd>〒160-0048 東京都青葉区月見台3-8-1</dd></div><div><dt>学級数</dt><dd>各学年6クラス／1クラス30〜34名</dd></div><div><dt>コース</dt><dd>探究コース・総合コース・国際コース</dd></div><div><dt>教育目標</dt><dd>自ら問い、対話し、未来をともにつくる</dd></div></dl>`)} `}
function learning(){return `${pageHead('LEARNING','学び','教科の知識を土台に、自分の問いを社会との接点まで育てます。')}${section(`<div class="section-head"><div><p class="eyebrow">THREE PATHS, ONE SPIRIT</p><h2>3つのコース</h2></div><p>コースは優劣ではなく、学び方の違い。共通の基礎を学びながら、関心に合わせて深めます。</p></div><div class="course-grid"><article class="course"><p class="eyebrow">01 / QUESTION</p><h3>探究コース</h3><p>「なぜ？」を起点に、観察・調査・制作を繰り返します。</p><ul><li>週2時間の探究ゼミ</li><li>地域・大学との共同研究</li><li>成果を社会へ発表</li></ul></article><article class="course"><p class="eyebrow">02 / CONNECT</p><h3>総合コース</h3><p>幅広い選択科目から、自分の得意と可能性を組み合わせます。</p><ul><li>文理横断の選択授業</li><li>資格・検定サポート</li><li>少人数の進路講座</li></ul></article><article class="course"><p class="eyebrow">03 / OPEN</p><h3>国際コース</h3><p>言葉と文化の違いを越えて、考えを伝え合う力を育てます。</p><ul><li>英語による協働授業</li><li>短期海外研修</li><li>多文化共生プロジェクト</li></ul></article></div>`)}${section(`<div class="split"><div>${img('classroom.jpg','教室で対話する生徒たち')}</div><div class="prose"><p class="eyebrow">INQUIRY PROJECT</p><h2>問いから始まる授業</h2><p class="lead">教室の外に出ると、<br>教科がつながって見えてくる。</p><p>1年次は「身近な違和感」を観察し、2年次は地域の課題と出会い、3年次は自分の進路につながるテーマを深めます。図書館で資料を探し、実験室で確かめ、まちの人に話を聞く。答えに近づく道筋そのものが、学びになります。</p>${button('#contact?type=お問い合わせ','学びについて聞く','text-link')}</div></div>`,'section section-tint')}${section(`<div class="section-head"><div><p class="eyebrow">PATHWAYS</p><h2>進路支援</h2></div><p>担任・進路室・外部講師がチームになり、選択の理由を自分の言葉にするところから伴走します。</p></div><div class="feature-grid"><article class="feature"><h3>面談の時間</h3><p>年3回の進路面談に加え、日常のちょっとした相談も歓迎しています。</p></article><article class="feature"><h3>探究と進路</h3><p>探究の成果を志望理由やポートフォリオに整理し、大学・社会との接点をつくります。</p></article><article class="feature"><h3>卒業生の声</h3><p>多様な分野で活躍する卒業生が、学びの選び方を語りに来ます。</p></article></div><div class="stats" style="margin-top:42px"><div class="stat"><strong>82%</strong><span>第一志望分野への進学率（2026年度デモ値）</span></div><div class="stat"><strong>14</strong><span>探究ゼミのテーマ数</span></div><div class="stat"><strong>32</strong><span>進路面談の年間実施数（学年平均）</span></div><div class="stat"><strong>96%</strong><span>卒業生アンケート回答率</span></div></div>`)} `}
function life(){return `${pageHead('LIFE & PLACES','学校生活・施設','学ぶ、食べる、話す、夢中になる。青葉の時間割は教室の外にも続いています。')}${section(`<div class="section-head"><div><p class="eyebrow">A DAY AT AOBA</p><h2>青葉の一日</h2></div><p>少し早く来て図書館で過ごす人、放課後に仲間と汗を流す人。自分のリズムを見つけられる一日です。</p></div><div class="day-flow"><div><time>08:20</time><b>登校・朝の対話</b><span>教室の窓を開け、今日の予定を確認。</span></div><div><time>08:50</time><b>午前の授業</b><span>教科の土台を、対話と実験で深める。</span></div><div><time>12:35</time><b>昼休み</b><span>中庭、食堂、図書館。過ごし方は自由。</span></div><div><time>13:25</time><b>午後の授業</b><span>コース授業と探究ゼミの時間。</span></div><div><time>16:10</time><b>放課後</b><span>部活、委員会、進路室、もう一つの学び。</span></div></div>`)}${section(`<div class="section-head"><div><p class="eyebrow">PLACES TO GROW</p><h2>6つの場所</h2></div><p>用途を固定しすぎない場所が、思いがけない出会いを生みます。</p></div><div class="facility-grid"><article class="facility">${img('library.jpg','本棚が並ぶ図書館')}<div class="facility-body"><h3>月影図書館</h3><p>約6万冊。個人席、対話テーブル、夜の読書室を備えた知の居場所です。</p></div></article><article class="facility">${img('classroom.jpg','明るい教室で学ぶ生徒')}<div class="facility-body"><h3>対話の教室</h3><p>机を動かして学び方を変えられる、柔軟なレイアウトの普通教室。</p></div></article><article class="facility">${img('campus.jpg','校舎と水辺の景色')}<div class="facility-body"><h3>水辺のテラス</h3><p>朝の読書や昼のランチに。季節の変化を感じる中庭です。</p></div></article><article class="facility">${img('classroom.jpg','学習スペースの様子')}<div class="facility-body"><h3>理科実験室</h3><p>観察から分析まで、探究の仮説を確かめるための実験設備。</p></div></article><article class="facility">${img('basketball.jpg','バスケットボールコート')}<div class="facility-body"><h3>第一体育館</h3><p>バスケットボール、バレーボール、式典にも使う大きな活動空間。</p></div></article><article class="facility">${img('students.jpg','校舎の外で過ごす生徒たち')}<div class="facility-body"><h3>メディア工房</h3><p>写真・音声・映像を通して、伝える力を試せる制作スタジオ。</p></div></article></div>`,'section section-tint')}${section(`<div class="section-head"><div><p class="eyebrow">ANNUAL CALENDAR</p><h2>年間行事</h2></div></div><dl class="rule-list"><div><dt>4月</dt><dd>入学式／新入生オリエンテーション／コースガイダンス</dd></div><div><dt>6月</dt><dd>青葉祭・文化の部／地域フィールドワーク</dd></div><div><dt>7月</dt><dd>夏季探究ゼミ／短期海外研修</dd></div><div><dt>9月</dt><dd>青葉祭・体育の部／進路ウィーク</dd></div><div><dt>11月</dt><dd>探究発表会／芸術鑑賞会</dd></div><div><dt>3月</dt><dd>卒業式／次年度へのポートフォリオ対話</dd></div></dl>`)} `}
function clubCard(c){return `<article class="club" data-club-type="${c.type}"><span class="tag">${c.type}</span><h3>${c.name}</h3><p>${c.body}</p><div class="club-meta">活動日：${c.days}<br>場所：${c.place}</div><details class="club-detail"><summary>紹介詳細を見る</summary><p>${c.name}は、${c.type==='運動部'?'基礎練習と対話を重ね、体力だけでなく判断力と仲間を信じる力を育てます。':'観察・表現・制作を通して、放課後の時間を一つの作品や発見に変えていきます。'} 見学では普段の練習や活動の雰囲気を体験できます。</p><a href="#contact?type=部活動見学">見学を相談する →</a></details></article>`}
function clubsPage(){return `${pageHead('CLUBS','部活動','放課後の熱中は、教室で見つけた自分とは違う一面を教えてくれます。')}${section(`<div class="section-head"><div><p class="eyebrow">AFTER SCHOOL</p><h2>好きなことを、<br>好きな仲間と。</h2></div><p>活動日は目安です。見学・体験は各部の紹介を読んだうえで、お問い合わせください。</p></div><div class="filter-bar" role="group" aria-label="部活動の分類"><span class="muted">絞り込み：</span><button class="filter-button" data-club-filter="すべて" aria-pressed="true">すべて</button><button class="filter-button" data-club-filter="運動部" aria-pressed="false">運動部</button><button class="filter-button" data-club-filter="文化部" aria-pressed="false">文化部</button></div><div class="club-grid" data-clubs>${clubs.map(clubCard).join('')}</div>`)} `}
function admissions(){return `${pageHead('ADMISSIONS','入試・説明会','2027年度入試のデモ要項と、青葉を体験できる3つの機会をご案内します。')}${section(`<div class="event-note"><div><b>受験生・保護者のみなさまへ</b><br><span class="muted">説明会はすべて予約制です。1組2名まで、参加費はかかりません。</span></div>${button('#admissions/reserve','説明会を予約','button button-dark')}</div><div class="section-head"><div><p class="eyebrow">OPEN SCHOOL</p><h2>説明会の日程</h2></div><p>学校の説明だけでなく、授業・施設・人に触れられる時間を用意しています。</p></div><div class="schedule"><article class="schedule-card"><time>10.18 SUN</time><h3>秋の学校説明会</h3><p>10:00–12:30／授業見学、学校説明、在校生座談会</p>${button('#admissions/reserve?event=秋の学校説明会','この回を予約','text-link')}</article><article class="schedule-card"><time>11.08 SUN</time><h3>探究授業体験会</h3><p>13:00–15:30／ミニ探究、施設見学、個別相談</p>${button('#admissions/reserve?event=探究授業体験会','この回を予約','text-link')}</article><article class="schedule-card"><time>12.06 SUN</time><h3>入試直前相談会</h3><p>09:30–12:00／入試説明、過去問解説、個別相談</p>${button('#admissions/reserve?event=入試直前相談会','この回を予約','text-link')}</article></div>`)}${section(`<div class="section-head"><div><p class="eyebrow">2027 ADMISSIONS</p><h2>入試要項（デモ）</h2></div><p>正式な募集要項は、入試年度の秋に公開します。以下はサイト体験用の架空情報です。</p></div><table class="data-table"><tr><th>募集区分</th><td>普通科／探究・総合・国際コース</td></tr><tr><th>募集人数</th><td>180名（推薦・一般 合計）</td></tr><tr><th>出願期間</th><td>2027年1月12日（火）〜1月22日（金）</td></tr><tr><th>選考</th><td>国語・数学・英語、面接、調査書</td></tr><tr><th>合格発表</th><td>2027年2月12日（金）</td></tr></table>`,'section section-tint')}${section(`<div class="section-head"><div><p class="eyebrow">COST</p><h2>学費・諸費用（年額）</h2></div></div><table class="fee-table"><tr><th>入学金</th><td>250,000円</td></tr><tr><th>授業料</th><td>420,000円</td></tr><tr><th>施設維持費</th><td>96,000円</td></tr><tr><th>ICT・教材費</th><td>78,000円</td></tr><tr><th>制服・体育用品（初年度）</th><td>約110,000円</td></tr></table><p class="muted" style="margin-top:14px">※すべて架空のデモ情報です。奨学金・就学支援金については個別相談でご案内します。</p>`)} `}
function newsPage(){const cats=['すべて',...new Set(news.map(n=>n.cat))];return `${pageHead('NEWS','お知らせ','学校の出来事、学びの様子、入試に関する案内をお届けします。')}${section(`<div class="filter-bar" role="group" aria-label="お知らせの分類">${cats.map((c,i)=>`<button class="filter-button" data-news-filter="${c}" aria-pressed="${i===0}">${c}</button>`).join('')}</div><div class="news-list" data-news-list>${news.map(newsRow).join('')}</div>`)} `}
function newsDetail(id){const n=news.find(x=>x.id===id);if(!n)return notFound();return `${pageHead('NEWS / DETAIL','お知らせ','青葉高等学校からのご案内')}${section(`<article class="prose"><div class="eyebrow">${n.cat} ／ ${n.date}</div><h2 style="font-family:var(--serif);font-size:clamp(30px,5vw,48px);font-weight:400;line-height:1.45">${n.title}</h2><p class="lead">${n.body}</p><p>青葉高等学校では、学校の中で起きていることを、できるだけ開いてお伝えしています。当日の様子や参加方法についてご不明な点があれば、いつでもお問い合わせください。</p><p>見学をご希望の方は、説明会の日程をご確認のうえお申し込みください。日程が合わない場合は個別相談も承ります。</p><div style="margin-top:30px">${button('#news','お知らせ一覧へ','text-link')}　${button('#contact','お問い合わせ','text-link')}</div></article>`)} `}
function access(){return `${pageHead('ACCESS & FAQ','アクセス・FAQ','月見台駅から徒歩8分。初めての方にもわかりやすい道順と、よくある質問をご案内します。')}${section(`<div class="split"><div><p class="eyebrow">FIND US</p><h2>学校への道</h2><p class="lead">月見台駅から、<br>水辺の遊歩道をまっすぐ。</p><p>〒160-0048 東京都青葉区月見台3-8-1<br>電話：03-0000-1968（平日9:00〜17:00）</p><ol><li>月見台駅 西口を出て、駅前広場を左へ。</li><li>青葉川沿いの遊歩道を約600m進む。</li><li>白い時計塔が見えたら、横断歩道を渡る。</li><li>正門の受付で来校目的をお伝えください。</li></ol>${button('#contact?type=お問い合わせ','道順を問い合わせる','text-link')}</div><div class="map-box" role="img" aria-label="月見台駅から青葉高等学校までの概略図"><span class="map-label station">月見台駅 西口</span><span class="map-label school">青葉高等学校 正門</span><span class="map-label gate">受付</span></div></div>`)}${section(`<div class="section-head"><div><p class="eyebrow">QUESTIONS</p><h2>よくある質問</h2></div><p>見学・入試・学校生活について、よくいただく質問をまとめました。</p></div><div class="faq"><details><summary>説明会には予約が必要ですか？</summary><p>はい、すべて予約制です。日程を選んで、氏名・メールアドレス・参加人数を入力してください。当日は受付で予約完了画面をご提示ください。</p></details><details><summary>説明会の日程が合わない場合は見学できますか？</summary><p>個別相談・見学を受け付けています。お問い合わせフォームから希望日をお知らせください。</p></details><details><summary>コースはいつ決めますか？</summary><p>入学時に希望コースを選択します。入学後も担任や進路室と相談しながら、学び方を見直せる機会を設けています。</p></details><details><summary>部活動は掛け持ちできますか？</summary><p>活動時間が重ならない範囲で、文化部と委員会などを組み合わせることができます。</p></details><details><summary>制服はありますか？</summary><p>基本制服を用意しています。式典時の着用を基本とし、季節や活動に合わせた選択肢も検討しています。</p></details><details><summary>昼食はどうしていますか？</summary><p>食堂のランチ、購買のお弁当、持参のお弁当を利用できます。中庭や食堂など、好きな場所で昼休みを過ごせます。</p></details><details><summary>最寄り駅からの所要時間は？</summary><p>月見台駅西口から徒歩約8分です。雨天時は遊歩道が滑りやすくなるため、時間に余裕を持ってお越しください。</p></details></div>`,'section section-tint')}${section(`<div class="split"><div><p class="eyebrow">SCHOOL GUIDE</p><h2>印刷用学校案内</h2><p>学校概要・3コース・説明会日程を1枚にまとめた印刷用の案内です。</p></div>${button('#brochure','学校案内を開く','button button-dark')}</div>`)} `}
function contactForm(){return `<div class="form-steps"><div class="form-step active">1　入力</div><div class="form-step">2　確認</div><div class="form-step">3　完了</div></div><form data-contact-form novalidate><div class="form-grid"><div class="field"><label for="contact-type">お問い合わせ種別<span class="required">必須</span></label><select id="contact-type" name="type" required><option value="">選択してください</option><option>資料請求</option><option>お問い合わせ</option><option>部活動見学</option><option>個別相談</option></select><p class="error" data-error-for="type"></p></div><div class="field"><label for="contact-name">お名前<span class="required">必須</span></label><input id="contact-name" name="name" required><p class="error" data-error-for="name"></p></div><div class="field"><label for="contact-email">メールアドレス<span class="required">必須</span></label><input id="contact-email" name="email" type="email" required placeholder="example@aoba.example"><p class="error" data-error-for="email"></p></div><div class="field"><label for="contact-tel">電話番号（任意）</label><input id="contact-tel" name="tel" inputmode="tel" placeholder="03-0000-1968"></div><div class="field full"><label for="contact-message">お問い合わせ内容<span class="required">必須</span></label><textarea id="contact-message" name="message" required placeholder="ご質問、見学希望日などをご入力ください"></textarea><p class="error" data-error-for="message"></p></div><div class="field full"><label><input type="checkbox" name="agree" required> 個人情報の取り扱いに同意する<span class="required">必須</span></label><p class="error" data-error-for="agree"></p></div></div><div class="form-actions"><button type="submit" class="button button-dark">入力内容を確認する →</button></div></form>`}
function reserveForm(eventName=''){return `<div class="form-steps"><div class="form-step active">1　入力</div><div class="form-step">2　確認</div><div class="form-step">3　完了</div></div><form data-reserve-form novalidate><div class="form-grid"><div class="field full"><label for="reserve-event">参加する説明会<span class="required">必須</span></label><select id="reserve-event" name="event" required><option value="">選択してください</option>${['秋の学校説明会','探究授業体験会','入試直前相談会'].map(e=>`<option ${eventName===e?'selected':''}>${e}</option>`).join('')}</select><p class="error" data-error-for="event"></p></div><div class="field"><label for="reserve-name">お名前<span class="required">必須</span></label><input id="reserve-name" name="name" required><p class="error" data-error-for="name"></p></div><div class="field"><label for="reserve-email">メールアドレス<span class="required">必須</span></label><input id="reserve-email" name="email" type="email" required><p class="error" data-error-for="email"></p></div><div class="field"><label for="reserve-count">参加人数<span class="required">必須</span></label><select id="reserve-count" name="count" required><option value="">選択してください</option><option>1名</option><option>2名</option></select><p class="error" data-error-for="count"></p></div><div class="field"><label for="reserve-grade">受験生の学年</label><select id="reserve-grade" name="grade"><option>中学3年</option><option>中学2年</option><option>中学1年</option><option>その他</option></select></div><div class="field full"><label><input type="checkbox" name="agree" required> 個人情報の取り扱いに同意する<span class="required">必須</span></label><p class="error" data-error-for="agree"></p></div></div><div class="form-actions"><a class="button button-quiet" href="#admissions">日程に戻る</a><button type="submit" class="button button-dark">入力内容を確認する →</button></div></form>`}
function contact(type=''){return `${pageHead('CONTACT','お問い合わせ・資料請求','ご質問や資料請求はこちらから。入力内容はこのデモ画面の中だけで確認し、保存・送信は行いません。')}${section(`<div class="form-shell" data-form-shell data-prefill-type="${type}">${contactForm(type)}</div>`)} `}
function reserve(eventName=''){return `${pageHead('EVENT RESERVATION','説明会予約','参加したい回を選び、必要事項を入力してください。これは送信されないローカルデモです。')}${section(`<div class="form-shell" data-form-shell>${reserveForm(eventName)}</div>`)} `}
function students(){return `${pageHead('FOR STUDENTS','在校生の方へ','今日の予定から、困ったときの相談先まで。青葉で過ごす毎日を支える案内です。')}${section(`<div class="feature-grid"><article class="feature"><h3>今週の予定</h3><p>9/14（月）コース別ガイダンス<br>9/16（水）図書委員会<br>9/18（金）探究ゼミ中間発表</p></article><article class="feature"><h3>学習サポート</h3><p>放課後の質問教室は月・水・木の16:30〜18:00。進路室では予約なしの相談も受け付けています。</p></article><article class="feature"><h3>相談窓口</h3><p>担任、保健室、スクールカウンセラー。直接話しにくい時は、職員室前の相談ボックスも使えます。</p></article></div>`)}${section(`<div class="split"><div class="prose"><p class="eyebrow">STUDENT HANDBOOK</p><h2>自分たちの学校を、<br>自分たちでつくる。</h2><p>委員会・行事・探究活動では、生徒の提案が学校の風景を変えていきます。図書館の開館時間、文化祭のテーマ、制服の選択肢も、対話から始まりました。</p>${button('#contact?type=お問い合わせ','在校生向けに問い合わせる','text-link')}</div>${img('library.jpg','図書館で本を読む人')}</div>`,'section section-tint')}`}
function alumni(){return `${pageHead('FOR ALUMNI','卒業生の方へ','青葉で育ったつながりを、次の世代へ。卒業生向けのご案内です。')}${section(`<div class="split"><div><p class="eyebrow">ALUMNI VOICES</p><h2 class="quote">卒業してからも、<br>問いは続いていく。</h2></div><div class="prose"><p>卒業生は、大学・企業・地域のさまざまな場所で、自分の問いを育てています。学校では年2回の卒業生交流会と、在校生向けの進路トークを開催しています。</p><p>住所変更、講演・取材の相談、同窓会活動の掲載依頼はお問い合わせフォームからお知らせください。</p>${button('#contact?type=お問い合わせ','卒業生窓口へ','text-link')}</div></div>`)}${section(`<div class="rule-list"><div><dt>交流会</dt><dd>2026年11月21日（土） 14:00〜／月影図書館</dd></div><div><dt>進路トーク</dt><dd>在校生に向けた仕事・学びの話を随時募集しています。</dd></div><div><dt>証明書発行</dt><dd>卒業証明書・成績証明書は事務室へお問い合わせください。</dd></div></div>`,'section section-tint')}`}
function privacy(){return `${pageHead('PRIVACY','プライバシー','青葉高等学校デモサイトにおける情報の取り扱いについて')}${section(`<div class="prose"><h2>個人情報の取り扱い</h2><p>このサイトは架空の学校サイトを再現したデモです。お問い合わせ・説明会予約フォームに入力した情報は、ブラウザ内で確認画面を表示するためだけに利用し、サーバーへ送信・保存しません。</p><h3>取得する情報</h3><p>お名前、メールアドレス、電話番号、参加人数など、入力フォームに記載された情報を一時的に扱います。</p><h3>外部サービス</h3><p>このデモは外部の解析・広告・認証サービスを利用していません。写真クレジットはフッターからご確認いただけます。</p><h3>お問い合わせ</h3><p>本サイトに関するお問い合わせは、実在の学校窓口ではなく、このデモの制作者にご連絡ください。</p></div>`)} `}
function sitemap(){const links=[['学校紹介','#about'],['学び','#learning'],['学校生活・施設','#life'],['部活動','#clubs'],['入試・説明会','#admissions'],['お知らせ','#news'],['アクセス・FAQ','#access'],['お問い合わせ・資料請求','#contact'],['在校生の方へ','#students'],['卒業生の方へ','#alumni'],['プライバシー','#privacy'],['印刷用学校案内','#brochure']];return `${pageHead('SITEMAP','サイトマップ','青葉高等学校デモサイトの全ページをご案内します。')}${section(`<div class="feature-grid">${links.map(l=>`<a class="feature" href="${l[1]}"><h3>${l[0]}</h3><span class="text-link">ページを見る</span></a>`).join('')}</div>`)} `}
function brochure(){return `<div class="print-area"><div class="wrap"><p class="eyebrow">AOBA HIGH SCHOOL / SCHOOL GUIDE 2027</p><h1 style="font-family:var(--serif);font-size:clamp(40px,7vw,84px);font-weight:400;line-height:1.15;margin:20px 0">好きが、<br>未来をひらく。</h1>${img('campus.jpg','青葉高等学校のイメージ写真','brochure-photo')}<div class="split" style="margin-top:32px"><div><h2>青葉高等学校</h2><p>1968年創立。探究・総合・国際の3コース、各学年6クラス。自ら問い、対話し、未来をともにつくる学びを実践しています。</p></div><div><h2>説明会</h2><p>10/18（日）秋の学校説明会<br>11/08（日）探究授業体験会<br>12/06（日）入試直前相談会</p></div></div><div class="form-actions"><a class="button button-quiet" href="#home">サイトへ戻る</a><button class="button button-dark" onclick="window.print()">この案内を印刷する</button></div></div></div>`}
function notFound(){return `${pageHead('404','ページが見つかりません','お探しのページは移動したか、URLが間違っている可能性があります。')}${section(`<div class="empty">${button('#home','トップへ戻る','button button-dark')}</div>`)} `}
function parseRoute(){const raw=location.hash.slice(1)||'home';const [path,query='']=raw.split('?');return {path:path.replace(/^\//,'')||'home',params:new URLSearchParams(query)}}
function render(){const {path,params}=parseRoute();let html='';if(path==='home')html=home();else if(path==='about')html=about();else if(path==='learning')html=learning();else if(path==='life')html=life();else if(path==='clubs')html=clubsPage();else if(path==='admissions')html=admissions();else if(path==='admissions/reserve')html=reserve(params.get('event')||'');else if(path==='news')html=newsPage();else if(path.startsWith('news/'))html=newsDetail(path.split('/')[1]);else if(path==='access')html=access();else if(path==='contact')html=contact(params.get('type')||'');else if(path==='students')html=students();else if(path==='alumni')html=alumni();else if(path==='privacy')html=privacy();else if(path==='sitemap')html=sitemap();else if(path==='brochure')html=brochure();else html=notFound();main.innerHTML=html;main.focus({preventScroll:true});nav.classList.remove('is-open');document.querySelector('[data-menu-toggle]').setAttribute('aria-expanded','false');bindPage();window.scrollTo(0,0)}
function bindPage(){document.querySelectorAll('[data-club-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-club-filter]').forEach(b=>b.setAttribute('aria-pressed',b===btn));const type=btn.dataset.clubFilter;document.querySelectorAll('[data-club-type]').forEach(card=>card.hidden=type!=='すべて'&&card.dataset.clubType!==type)}));document.querySelectorAll('[data-news-filter]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-news-filter]').forEach(b=>b.setAttribute('aria-pressed',b===btn));const cat=btn.dataset.newsFilter;document.querySelectorAll('[data-news-list] .news-row').forEach((row,i)=>row.hidden=cat!=='すべて'&&news[i].cat!==cat)}));const cform=document.querySelector('[data-contact-form]');if(cform)cform.addEventListener('submit',e=>handleForm(e,'contact'));const rform=document.querySelector('[data-reserve-form]');if(rform)rform.addEventListener('submit',e=>handleForm(e,'reserve'))}
function validate(form){let valid=true;form.querySelectorAll('.error').forEach(e=>e.textContent='');form.querySelectorAll('[required]').forEach(field=>{let msg='';if(field.type==='checkbox'&&!field.checked)msg='同意が必要です。';else if(!field.value.trim())msg='入力してください。';else if(field.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(field.value))msg='メールアドレスの形式をご確認ください。';if(msg){valid=false;form.querySelector(`[data-error-for="${field.name}"]`).textContent=msg}});return valid}
function handleForm(e,kind){e.preventDefault();const form=e.currentTarget;if(!validate(form)){form.querySelector('.error:not(:empty)')?.parentElement?.querySelector('input,select,textarea')?.focus();return}const data=Object.fromEntries(new FormData(form));const shell=form.closest('[data-form-shell]');const title=kind==='reserve'?'説明会予約':'お問い合わせ・資料請求';shell.innerHTML=`<div class="form-steps"><div class="form-step">1　入力</div><div class="form-step active">2　確認</div><div class="form-step">3　完了</div></div><div class="confirmation"><div class="check" aria-hidden="true">✓</div><p class="eyebrow">LOCAL DEMO CONFIRMATION</p><h2 style="font-family:var(--serif);font-size:32px;font-weight:400">入力内容をご確認ください</h2><p>以下の内容でよろしければ「この内容で完了」を押してください。外部送信や保存は行いません。</p><dl class="rule-list">${Object.entries(data).filter(([k])=>k!=='agree').map(([k,v])=>`<div><dt>${labelFor(k)}</dt><dd>${escapeHtml(v)}</dd></div>`).join('')}</dl><div class="form-actions"><button class="button button-quiet" data-form-back type="button">入力に戻る</button><button class="button button-dark" data-form-complete type="button">この内容で完了</button></div></div>`;shell.querySelector('[data-form-back]').addEventListener('click',()=>{shell.innerHTML=kind==='reserve'?reserveForm(data.event):contactForm();bindPage();Object.entries(data).forEach(([k,v])=>{const el=shell.querySelector(`[name="${k}"]`);if(el&&el.type!=='checkbox')el.value=v;if(el&&el.type==='checkbox')el.checked=true})});shell.querySelector('[data-form-complete]').addEventListener('click',()=>{shell.innerHTML=`<div class="form-steps"><div class="form-step">1　入力</div><div class="form-step">2　確認</div><div class="form-step active">3　完了</div></div><div class="confirmation"><div class="check" aria-hidden="true">✓</div><p class="eyebrow">DEMO COMPLETE</p><h2 style="font-family:var(--serif);font-size:32px;font-weight:400">${title}を受け付けました</h2><p>ご入力ありがとうございました。これはローカルデモのため、実際のメール送信や資料発送は行われません。</p><div class="form-actions">${button(kind==='reserve'?'#admissions':'#home','ページへ戻る','button button-dark')}</div></div>`})}
function labelFor(k){return ({type:'種別',event:'参加説明会',name:'お名前',email:'メールアドレス',tel:'電話番号',message:'内容',count:'参加人数',grade:'学年'})[k]||k}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const dialog=document.querySelector('[data-search-dialog]');
let searchReturnFocus=null;
function openSearch(){searchReturnFocus=document.activeElement;dialog.setAttribute('aria-hidden','false');document.querySelector('#search-input').focus()}
function closeSearch(){dialog.setAttribute('aria-hidden','true');const target=searchReturnFocus&&searchReturnFocus.isConnected?searchReturnFocus:document.querySelector('[data-open-search]');searchReturnFocus=null;target?.focus()}
document.querySelector('[data-skip-link]').addEventListener('click',e=>{e.preventDefault();main.focus()});
dialog.addEventListener('click',e=>{if(e.target.closest('a.search-result'))closeSearch()});
dialog.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeSearch();return}if(e.key!=='Tab')return;const focusables=[...dialog.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),a[href]')];if(!focusables.length)return;const first=focusables[0],last=focusables[focusables.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
document.querySelector('[data-open-search]').addEventListener('click',openSearch);document.querySelectorAll('[data-close-search]').forEach(el=>el.addEventListener('click',closeSearch));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSearch();nav.classList.remove('is-open');document.querySelector('[data-menu-toggle]').setAttribute('aria-expanded','false')}});document.querySelector('[data-menu-toggle]').addEventListener('click',()=>{const open=nav.classList.toggle('is-open');document.querySelector('[data-menu-toggle]').setAttribute('aria-expanded',open)});document.querySelector('[data-search-form]').addEventListener('submit',e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('q').toString().trim().toLowerCase();const out=document.querySelector('[data-search-results]');if(!q){out.innerHTML='<p class="muted">キーワードを入力してください。</p>';return}const hits=searchable.filter(x=>(x.title+x.desc).toLowerCase().includes(q));out.innerHTML=hits.length?`<p class="muted">${hits.length}件見つかりました。</p>${hits.map(x=>`<a class="search-result" href="${x.href}"><b>${x.title}</b><small>${x.desc}</small></a>`).join('')}`:'<p class="empty">一致するページが見つかりませんでした。<br>別のキーワードをお試しください。</p>'});
function prefillContact(){const {path,params}=parseRoute();if(path==='contact'&&params.get('type')){const select=document.querySelector('[name="type"]');if(select)select.value=params.get('type')}}
window.addEventListener('hashchange',render);window.addEventListener('hashchange',prefillContact);render();prefillContact();
