'use strict';
const $=s=>document.querySelector(s), main=$('#main'), A='../school-comparison/assets/';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const photo=(name,alt,cls='')=>`<img src="${A+name}.jpg" alt="${alt}（イメージ写真）" class="${cls}" loading="lazy">`;
const link=(href,label,cls='text-link')=>`<a class="${cls}" href="#${href}">${label} <span aria-hidden="true">→</span></a>`;
const dates=['2026年9月26日（土）10:00–12:00','2026年10月17日（土）10:00–12:00','2026年11月14日（土）14:00–16:00'];
const news=[
 ['2026.09.07','入試情報','秋のオープンキャンパス、受付を開始しました','9月26日のオープンキャンパスでは、学校紹介に加え、在校生が校内をご案内します。探究の体験授業、部活動見学、個別相談の時間も設けました。中学1・2年生の方もご参加いただけます。','当日は開始30分前から受付を行います。上履きと筆記用具をお持ちください。参加費は無料です。保護者のみのご参加も受け付けています。','campus'],
 ['2026.09.03','学校生活','青葉祭2026「つなぐ」、準備が始まりました','今年の青葉祭のテーマは「つなぐ」。学年を越えて協力し、演劇、研究展示、音楽ステージをつくります。実行委員会では、来場者が迷わず楽しめる会場案内も生徒たちが考えています。','一般公開は10月3日を予定しています。展示とステージの時間割は、9月下旬にこちらのサイトでご案内します。','students'],
 ['2026.08.28','部活動','吹奏楽部、夏の定期演奏会を開催','吹奏楽部が夏の練習の成果を披露しました。クラシックから映画音楽まで、部員が選んだ曲目を演奏。初めて舞台に立つ1年生も、仲間と呼吸を合わせて最後まで演奏しました。','次の発表の場は青葉祭です。新入部員も随時募集しています。見学を希望する方は、学校説明会で活動場所をご確認ください。','students'],
 ['2026.08.22','学び','地域の川から考える、2年生の探究フィールドワーク','探究コースの2年生が地域の水辺で観察を行いました。水質、周辺の植生、人の利用のしかたなど、同じ場所を異なる視点で調べています。','集めたデータは授業で整理し、地域の方への提案につなげます。答えを急がず、観察と対話を重ねることを大切にしています。','campus'],
 ['2026.08.10','入試情報','2027年度 生徒募集要項を公開しました','2027年度の募集人数、選考方法、出願日程を掲載しました。総合・探究・国際の3コースで、生徒を募集します。','出願に関するご相談は説明会の個別相談でも承ります。本サイトの日程・金額は制作デモの架空情報です。','classroom'],
 ['2026.07.24','学び','国際コース、オンライン交流授業を実施','国際コースでは、海外の学校との交流を想定した英語の発表授業を実施しました。身近な食文化を題材に、調べたことを自分の言葉で伝えます。','相手に伝わる表現を仲間と考え、質疑応答ではその場で言葉を選ぶ経験を積みました。','classroom'],
 ['2026.07.17','学校生活','夏休みの図書館・自習室の開室時間','夏休み期間中は、平日9:00から16:00まで図書館と自習室を利用できます。8月10日から14日までは閉室します。','入室時に生徒証を提示してください。貸出期間を過ぎた本は、返却カウンターまたは返却ボックスへお戻しください。','library'],
 ['2026.07.12','部活動','バスケットボール部、練習試合で見つけた次の課題','バスケットボール部が近隣校との練習試合を行いました。試合後は映像を見ながら、声の掛け方と守備の連携を振り返りました。','勝敗だけでなく、毎日の練習で何を変えるかを言葉にする時間を大切にしています。夏は基礎体力づくりにも取り組みます。','basketball']
];
const clubs=[
 ['basketball','バスケットボール部','運動部','basketball','月・火・木・金・土','第1体育館','一人の一歩が、チームの力になる。','基礎練習と実戦形式の練習を組み合わせ、判断力と連携を磨きます。初心者には上級生がボールの扱い方から伴走。練習後の短いミーティングで、互いのよかったプレーを伝え合います。',36],
 ['football','サッカー部','運動部','campus','月・水・木・金・土','総合グラウンド','最後の笛まで、自分たちのサッカーを。','パスとポジショニングを大切に、全員でゴールを目指します。週末は近隣校との練習試合を実施。選手だけでなく、記録や用具の管理に関わる仲間も募集しています。',42],
 ['tennis','硬式テニス部','運動部','campus','月・火・木・土','テニスコート','一球に向き合う、静かな情熱。','基本のフォームを身につけるところから、ダブルスの戦術まで段階的に練習します。学年を越えたペア練習で、相手に伝える力も育ちます。ラケットの貸出があります。',24],
 ['track','陸上競技部','運動部','campus','月・水・金・土','総合グラウンド','昨日の自分を、一歩越える。','短距離、長距離、跳躍のグループに分かれ、自分の目標に合わせて練習します。フォームの撮影と記録の振り返りを通して、無理なく長く走れる身体をつくります。',28],
 ['music','吹奏楽部','文化部','students','月・火・木・金・土','音楽室・合奏室','違う音が、ひとつの音楽になる。','夏の演奏会と青葉祭を大きな目標に、パート練習と合奏を重ねます。楽器経験のない人も歓迎。地域の催しで演奏する機会もあり、音楽で人とつながる楽しさを味わえます。',48],
 ['art','美術部','文化部','classroom','火・木・金','美術室','あなたにしか見えない色がある。','絵画、立体、デザインなど、素材とテーマを自分で選んで制作します。互いの作品を見ながら意見を交わす時間と、集中して手を動かす時間の両方を大切にしています。',18],
 ['science','科学部','文化部','classroom','火・水・金','理科実験室','なぜ？から始まる、放課後の実験。','水質調査、生き物の観察、ものづくりなど、興味に応じて小さな研究班をつくります。実験計画を先生と確認してから取り組み、青葉祭で成果を展示します。',20],
 ['literature','文芸・図書部','文化部','library','月・木','図書館','読むことから、伝えることへ。','読書会、短編小説の制作、図書館の展示企画を行います。好きな一冊を紹介するビブリオバトルも開催。読むのが好きな人も、書いてみたい人も歓迎します。',16]
];
const routeInfo={home:['ホーム','HOME',''],about:['青葉について','ABOUT AOBA','自分を知り、人と学び、社会とつながる。1968年から続く、青葉の教育。'],learning:['青葉の学び','LEARNING','一人ひとりの「好き」と「なぜ」を、学びの出発点に。'],life:['学校生活・施設','CAMPUS LIFE','教室も、放課後も。かけがえのない3年間が、ここにあります。'],clubs:['部活動','CLUB ACTIVITIES','夢中になれること。いっしょに笑える仲間。放課後に見つかる、もう一つの自分。'],admissions:['入試・説明会','ADMISSIONS','青葉で始まる、あなたの3年間。まずは学校に会いに来ませんか。'],news:['お知らせ','NEWS & TOPICS','青葉の日々と、学校からのご案内をお届けします。'],access:['アクセス・よくある質問','ACCESS & FAQ','ご来校の前に、交通案内とよくあるご質問をご確認ください。'],contact:['お問い合わせ・資料請求','CONTACT','学校生活や入試に関するご相談、学校案内のご請求はこちらから。'],reservation:['説明会のご予約','OPEN CAMPUS','見て、聞いて、体験する。青葉の一日を、あなた自身で。'],students:['在校生・保護者の方へ','FOR STUDENTS','学校からの連絡と、日々の手続きのご案内。'],graduates:['卒業生の方へ','FOR ALUMNI','卒業後も、青葉とのつながりを。証明書と同窓会のご案内。'],privacy:['プライバシーポリシー','PRIVACY','この制作デモにおける情報の取り扱いについて。'],sitemap:['サイトマップ','SITE MAP','目的のページへ直接お進みいただけます。']};
let newsFilter='すべて',clubFilter='すべて',draft=null;
function titlePage(key,body){const v=routeInfo[key];return `<div class="wrap breadcrumbs"><a href="#home">ホーム</a><span>／</span>${v[0]}</div><div class="page-title"><div class="wrap"><div class="eyebrow">${v[1]}</div><h1>${v[0]}</h1><p>${v[2]}</p></div></div><div class="wrap page-body">${body}</div>`}
function tabs(kind,values,current){return `<div class="tabs" aria-label="${kind==='news'?'お知らせ':'部活動'}の分類">${values.map(v=>`<button data-filter="${kind}" data-value="${v}" aria-pressed="${v===current}">${v}</button>`).join('')}</div>`}
function newsRows(list){return list.map(n=>`<a class="news-row" href="#news/${news.indexOf(n)}"><time>${n[0]}</time><span class="tag">${n[1]}</span><span class="news-title">${n[2]}</span><span class="arrow" aria-hidden="true">↗</span></a>`).join('')}
function visit(){return `<section class="visit"><div class="eyebrow">COME & MEET AOBA</div><h2>ここから始まる、未来の話。</h2><p>学校のことも、あなたのことも。まずは会って、お話ししましょう。</p><div class="actions">${link('admissions','説明会・オープンキャンパス','button')}${link('contact/material','学校案内を取り寄せる','button outline')}</div></section>`}
function home(){return `<section class="hero"><div class="hero-copy"><div class="eyebrow">GROW YOUR CURIOSITY. FIND YOUR FUTURE.</div><h1>好きが、<br>未来をひらく。</h1><p>「やってみたい」が、学びに変わる。<br>仲間と過ごす毎日が、自信に変わる。<br>あなたらしい未来を、青葉から。</p>${link('about','青葉の教育を知る')}</div><div class="hero-photo"><img src="${A}campus.jpg" alt="水辺と緑に囲まれた学びの場（イメージ写真）" fetchpriority="high"><span class="hero-stamp">一人ひとりの可能性と、ともに。</span></div></section><div class="wrap"><div class="hero-bottom"><b>AOBA HIGH SCHOOL — SINCE 1968</b><span>SCROLL TO EXPLORE ↓</span></div><div class="notice"><span>重要なお知らせ</span><a href="#news/4">2027年度 生徒募集要項を公開しました <b>→</b></a></div><div class="open-campus"><div><div class="eyebrow">2026 秋の学校見学</div><h2>OPEN CAMPUS</h2><p>まだ知らない青葉に、会いに来よう。</p></div><div class="event-side"><div><span class="date">9.26<small>SAT</small></span><span class="date-caption">10:00–12:00 ／ 中学生・保護者対象</span></div>${link('reservation/0','詳細・お申込み','button light')}</div></div></div><section class="section wrap news-layout"><div class="section-intro"><div class="eyebrow">NEWS & TOPICS</div><h2>青葉のいま。</h2>${link('news','お知らせ一覧')}</div><div>${tabs('home',['すべて','入試情報','学校生活','部活動'],'すべて')}<div id="home-news">${newsRows(news.slice(0,4))}</div></div></section><section class="paper section"><div class="wrap editorial">${photo('students','友人と過ごす学校の日々')}<div><div class="eyebrow">ABOUT OUR SCHOOL</div><h2>自分の問いを、<br>世界につなぐ。</h2><p>答えが一つではない時代に、大切なのは問い続ける力。<br>青葉では、小さな好奇心を見逃さず、仲間と考え、自分の言葉で伝える学びを育んでいます。</p><p>教室を飛び出して地域へ。興味を深めて、次の挑戦へ。<br>一人ひとりの歩幅を大切にする学校です。</p>${link('about','青葉について')}</div></div></section><section class="section wrap"><div class="heading-row"><div><div class="eyebrow">DISCOVER AOBA</div><h2>青葉で見つける、可能性。</h2></div></div><div class="feature-grid"><article class="feature"><a href="#learning">${photo('library','本から広がる学び')}<div class="numbered">01 / LEARNING</div><h3>「好き」を深める学び。</h3><p>3つのコースと探究の時間。自分らしい学び方を見つける。</p><span class="text-link">青葉の学び <span>→</span></span></a></article><article class="feature"><a href="#life">${photo('classroom','教室から見える学校生活')}<div class="numbered">02 / CAMPUS LIFE</div><h3>毎日が、特別になる。</h3><p>授業、行事、何気ない会話。3年間を彩る青葉の日常。</p><span class="text-link">学校生活・施設 <span>→</span></span></a></article><article class="feature"><a href="#clubs">${photo('basketball','光が差し込む体育館')}<div class="numbered">03 / CLUB ACTIVITIES</div><h3>夢中の、その先へ。</h3><p>挑戦を分かち合える仲間と、放課後の新しい自分に出会う。</p><span class="text-link">部活動紹介 <span>→</span></span></a></article></div></section>${visit()}`}
function about(){return titlePage('about',`<section class="split"><div><div class="eyebrow">OUR PHILOSOPHY</div><h2>知る喜びを、<br>生きる力に。</h2><p class="lede">自ら問い、ともに学び、<br>社会にひらかれた人へ。</p><p>青葉高等学校は、1968年の創立以来、一人ひとりの興味から学びを広げる教育を続けてきました。教科の基礎を丁寧に積み上げながら、答えの決まっていない問いに仲間と向き合います。</p><p>できることが増える喜びも、思うようにいかない経験も、自分を知る手がかりです。教員は対話を重ね、生徒が自分で選び、歩き出す過程を支えます。</p></div>${photo('campus','緑に開かれた学びの場所')}</section><div class="stats"><div><strong>1968</strong>創立年</div><div><strong>18</strong>全校クラス数</div><div><strong>3</strong>学びのコース</div></div><section class="split"><div><div class="eyebrow">MESSAGE</div><h2>まだ言葉にならない<br>可能性を、大切に。</h2></div><div><p>高校生活は、自分が何に心を動かされるのかを知る時間です。今、将来の目標が決まっていなくても大丈夫。まずは気になった本を開くこと、隣の人の考えを聞くことから始めてみてください。</p><p>青葉には、小さな挑戦を応援する先生と仲間がいます。3年後、自分の選んだ道に納得して進めるよう、私たちは日々の対話を大切にします。</p><p class="serif">校長　青木 直人 <small>（架空の人物）</small></p></div></section><section><h2>学校概要</h2><dl class="info"><dt>学校名</dt><dd>学校法人青葉学園 私立青葉高等学校</dd><dt>課程</dt><dd>全日制・普通科・男女共学</dd><dt>コース</dt><dd>総合コース・探究コース・国際コース</dd><dt>学級編成</dt><dd>各学年6クラス、全校18クラス</dd><dt>所在地</dt><dd>青葉県青葉市緑町1-8-1（架空）</dd></dl></section><section><h2>青葉のあゆみ</h2><div class="timeline"><div><strong>1968</strong><p>青葉高等学校開校。地域と学ぶ教育を始める。</p></div><div><strong>1998</strong><p>図書館棟が完成。自習・対話の空間を整備。</p></div><div><strong>2015</strong><p>全学年で探究学習を導入。</p></div><div><strong>2024</strong><p>3コース制へ。生徒の選択肢をさらに広げる。</p></div></div></section>`)}
function learning(){return titlePage('learning',`<section><div class="heading-row"><div><div class="eyebrow">THREE PATHS, YOUR FUTURE</div><h2>自分の学び方に、出会う。</h2></div></div><div class="feature-grid">${[['総合','幅広く学び、自分の軸をつくる。','基礎から発展まで教科を横断し、2年次から文系・理系の選択科目を組み合わせます。まだ進路を決めていない人も、幅広い経験から興味を探せます。'],['探究','問いを深め、社会に伝える。','週2時間の探究演習で、地域調査やデータ分析に取り組みます。大学の学びを想定した課題に挑み、論文と発表で自分の考えをまとめます。'],['国際','ことばを越えて、世界とつながる。','少人数の英語授業と発表演習を中心に、異なる文化や価値観に触れます。英語を学ぶことと、英語を使って学ぶことを行き来します。']].map((x,i)=>`<article class="course"><div class="numbered">COURSE 0${i+1}</div><h3>${x[0]}コース</h3><b>${x[1]}</b><p>${x[2]}</p><p class="fine">目安：各学年2クラス／1年次は共通基礎を重視</p></article>`).join('')}</div></section><section class="split">${photo('library','集中できる図書館')}<div><div class="eyebrow">INQUIRY BASED LEARNING</div><h2>「なぜ？」を、<br>学びの真ん中に。</h2><p>身近な課題を見つけ、調べ、対話し、提案する。探究の時間は、すべてのコースで取り組みます。1年次は調べ方と伝え方を学び、2年次はチーム研究、3年次は自分のテーマを深めます。</p><p>テーマ例：地域の川の水質／商店街の未来／学校でできる食品ロス対策／ことばと文化の違い。</p>${link('news/3','探究授業の様子を読む')}</div></section><section><h2>進路は、対話の先に。</h2><div class="timeline"><div><strong>01</strong><h3>自分を知る</h3><p>1年次：職業理解講座と担任面談で、自分の関心を言葉にします。</p></div><div><strong>02</strong><h3>選択肢を広げる</h3><p>2年次：大学見学や卒業生との対話を通して学問に出会います。</p></div><div><strong>03</strong><h3>目標を定める</h3><p>3年次前半：志望理由や学習計画を、個別面談で整理します。</p></div><div><strong>04</strong><h3>次の場所へ</h3><p>3年次後半：教科補習・小論文・面接練習で挑戦を支えます。</p></div></div></section><section><h2>卒業後の進路</h2><p class="fine">2025年度卒業生の架空データ。実際の進学実績ではありません。</p><div class="stats"><div><strong>76<small>%</small></strong>四年制大学</div><div><strong>18<small>%</small></strong>短大・専門学校</div><div><strong>6<small>%</small></strong>就職・その他</div></div><p>進学先の名称だけでなく、本人が納得して選んだかどうかを大切にします。総合型選抜、学校推薦型選抜、一般選抜など、目標に合う準備を個別に進めます。</p></section>`)}
function life(){const facilities=[['図書館','library','約30,000冊の蔵書と静かな閲覧席。司書が調べ学習や本選びを支えます。'],['普通教室','classroom','電子黒板を備え、個人学習からグループワークまで切り替えられる教室。'],['理科実験室','classroom','物理・化学・生物の実験室。安全を確認しながら、自分の手で確かめます。'],['体育館','basketball','授業、部活動、全校集会で使用。競技用コートとトレーニングの空間を備えます。'],['ラーニングコモンズ','library','会話しながら調べたり、発表の準備をしたり。学年を越えて学ぶ場所。'],['中庭・テラス','campus','昼休みに一息つける緑の空間。季節の移ろいも学校生活の一部です。']];return titlePage('life',`<section><h2>青葉の一日</h2><p>集中する時間も、ほっとする時間も。自分のペースで、毎日を積み重ねます。</p><div class="timeline">${[['8:30','朝のホームルーム','一日の予定を確認。読書や短い対話で気持ちを整えます。'],['8:50','午前の授業','50分授業を4時間。教科の基礎をじっくり学びます。'],['12:40','昼休み','お弁当や食堂で昼食。中庭や図書館で思い思いに過ごします。'],['13:30','午後・放課後','2時間の授業のあと、部活動・自習・委員会へ。完全下校は18:30。']].map(x=>`<div><strong>${x[0]}</strong><h3>${x[1]}</h3><p>${x[2]}</p></div>`).join('')}</div></section><section><h2>季節とともに、思い出が増える。</h2><div class="table-wrap"><table><thead><tr><th>季節</th><th>主な行事</th><th>青葉の楽しみ</th></tr></thead><tbody><tr><th>春 / 4–6月</th><td>入学式・新入生合宿・体育祭</td><td>クラスと学年を越えて、最初の仲間づくり。</td></tr><tr><th>夏 / 7–8月</th><td>探究発表・夏期講習・部活動合宿</td><td>いつもより長い時間を、自分の挑戦に。</td></tr><tr><th>秋 / 9–11月</th><td>青葉祭・修学旅行・芸術鑑賞</td><td>生徒主体でつくる文化祭が、学校を彩ります。</td></tr><tr><th>冬 / 12–3月</th><td>球技大会・探究成果発表・卒業式</td><td>一年の成長を振り返り、次の一歩へ。</td></tr></tbody></table></div></section><section><div class="eyebrow">OUR CAMPUS</div><h2>学ぶ場所も、居場所も。</h2><div class="facilities">${facilities.map((x,i)=>`<article class="facility">${photo(x[1],x[0])}<div class="numbered">FACILITY 0${i+1}</div><h3>${x[0]}</h3><p>${x[2]}</p></article>`).join('')}</div><p class="fine muted">写真は各施設の雰囲気を伝えるためのイメージです。</p></section>`)}
function clubCards(){const list=clubs.filter(c=>clubFilter==='すべて'||c[2]===clubFilter);return `<p class="fine muted" aria-live="polite">${list.length}件の部活動</p><div class="club-grid">${list.map(c=>`<article class="club">${photo(c[3],c[1]+'の活動イメージ')}<span class="tag">${c[2]}</span><h3>${c[1]}</h3><p>${c[6]}</p><p>活動日：${c[4]}</p>${link('clubs/'+c[0],'活動を詳しく見る')}</article>`).join('')}</div>`}
function clubPage(id){if(id){const c=clubs.find(c=>c[0]===id);if(!c)return missing();return titlePage('clubs',`<article class="article"><span class="tag">${c[2]}</span><h2>${c[1]}</h2><p class="lede">${c[6]}</p>${photo(c[3],c[1]+'の活動イメージ','article-image')}<p>${c[7]}</p><dl class="info"><dt>活動日</dt><dd>${c[4]}</dd><dt>活動場所</dt><dd>${c[5]}</dd><dt>部員数</dt><dd>${c[8]}名（架空設定）</dd><dt>活動時間</dt><dd>平日 15:45–18:00／土曜 9:00–12:00</dd><dt>見学</dt><dd>説明会でご相談ください。体験には運動着などをご案内します。</dd></dl><div class="actions" style="margin-top:30px">${link('clubs','部活動一覧へ','button outline')}${link('reservation/0','見学できる説明会へ','button')}</div></article>`)}return titlePage('clubs',`${tabs('clubs',['すべて','運動部','文化部'],clubFilter)}<div id="club-list">${clubCards()}</div>`)}
function admissions(){return titlePage('admissions',`<section><div class="eyebrow">OPEN CAMPUS 2026</div><h2>学校に、会いに来よう。</h2><p>生徒が案内する校内ツアー、体験授業、個別相談。パンフレットだけでは伝わらない青葉を体感してください。</p>${dates.map((d,i)=>`<article class="event"><div><span class="date">${['9.26','10.17','11.14'][i]}<small>SAT</small></span><span class="date-caption">2026年／参加無料</span></div><div><h3>${['秋のオープンキャンパス','学校説明会・部活動見学','入試対策説明会'][i]}</h3><p>${d}<br>${['体験授業・校内ツアー・個別相談','教育方針説明・部活動見学・在校生との交流','入試のポイント・出願案内・個別相談'][i]}</p></div>${link('reservation/'+i,'予約する','button')}</article>`).join('')}<p class="fine muted">中学生・保護者対象。要予約。掲載日程はデモ用の架空情報です。</p></section><section><h2>2027年度 生徒募集要項</h2><dl class="info"><dt>募集定員</dt><dd>普通科240名（総合・探究・国際 各80名）</dd><dt>推薦入試</dt><dd>出願：2027年1月8日–15日／試験：1月22日<br>選考：作文・面接・調査書</dd><dt>一般入試</dt><dd>出願：2027年1月25日–2月3日／試験：2月10日<br>選考：国語・数学・英語・面接</dd><dt>出願資格</dt><dd>2027年3月に中学校を卒業見込みの方、または同等の資格を有する方。推薦は在籍校の推薦を要します。</dd><dt>合格発表</dt><dd>推薦：1月26日／一般：2月15日</dd></dl><p class="fine muted">実際の出願はできません。この要項は架空の学校のデモです。</p></section><section><h2>学費のご案内</h2><div class="table-wrap"><table><thead><tr><th>費目</th><th>金額（架空）</th><th>納入時期</th></tr></thead><tbody><tr><th>入学金</th><td>200,000円</td><td>入学手続き時</td></tr><tr><th>授業料</th><td>年額420,000円</td><td>4期分納</td></tr><tr><th>施設設備費</th><td>年額120,000円</td><td>4期分納</td></tr><tr><th>教育充実費</th><td>年額60,000円</td><td>4期分納</td></tr><tr><th>初年度合計</th><td>800,000円</td><td>制服・教材・旅行積立などは別途</td></tr></tbody></table></div><p class="fine">奨学制度などのご相談は、説明会の個別相談を選択してください。実在する公的支援制度の案内ではありません。</p><div class="actions"><a class="button outline" href="guide.html" target="_blank">学校案内を読む・印刷する ↗</a>${link('access','よくある質問')}</div></section>`)}
function newsPage(id){if(id!==undefined){const n=news[Number(id)];if(!n)return missing();return titlePage('news',`<article class="article"><p><time>${n[0]}</time> <span class="tag">${n[1]}</span></p><h2>${n[2]}</h2>${photo(n[5],n[1]+'のイメージ','article-image')}<p>${n[3]}</p><p>${n[4]}</p>${n[1]==='入試情報'?link('admissions','入試・説明会を見る','button'):''}<p style="margin-top:35px">${link('news','お知らせ一覧に戻る')}</p></article>`)}return titlePage('news',`${tabs('news',['すべて','入試情報','学校生活','部活動','学び'],newsFilter)}<div id="news-list">${newsRows(news.filter(n=>newsFilter==='すべて'||n[1]===newsFilter))}</div>`)}
const faqs=[['説明会は保護者だけでも参加できますか？','はい。保護者の方のみ、中学1・2年生の方もご参加いただけます。予約フォームで人数を選択してください。'],['部活動と勉強は両立できますか？','定期考査前は部活動を休止し、学習時間を確保します。部活動ごとに活動日が異なるため、紹介ページで確認してください。'],['お弁当を持参する必要はありますか？','お弁当の持参に加え、食堂や購買を利用する想定です。食物アレルギーなどのご相談は、入学前に個別に伺います。'],['コースはいつ選びますか？','出願時に希望コースを選びます。入学後は面談を通して適性や希望を確認します。変更は履修状況を踏まえた相談が必要です。'],['自転車通学はできますか？','許可制です。通学経路と駐輪場所を確認し、安全講習を受けていただく想定です。'],['校内でスマートフォンは使えますか？','授業中は教員の指示がある場合に使用します。学校生活に必要なルールは、入学時のオリエンテーションで確認します。'],['資料請求や予約は本当に送信されますか？','このサイトは架空校のデモのため、送信・予約登録・郵送は行いません。フォームは入力、確認、完了までを体験できます。']];
function access(){return titlePage('access',`<section class="split"><div><h2>緑の道を歩いて、青葉へ。</h2><p>青葉線「青葉台駅」南口から徒歩12分。駅前通りをまっすぐ進み、緑町公園を左に見ながら坂を上がると正門があります。</p><dl class="info"><dt>所在地</dt><dd>青葉県青葉市緑町1-8-1</dd><dt>バス</dt><dd>青葉台駅南口から「緑町循環」→「青葉高校前」下車 徒歩2分</dd><dt>来校受付</dt><dd>正門右手の事務室へお越しください。</dd></dl><p class="fine muted">地名・交通機関・地図は架空です。実際の経路案内には利用できません。</p></div><div class="map" role="img" aria-label="架空の案内図。青葉台駅から駅前通りを通り、緑町公園の隣の青葉高等学校へ。"><div>青葉台駅 南口</div><div>緑町公園</div><div class="road">駅前通り　→　徒歩12分</div><div>バス停<br>青葉高校前</div><div class="school">青葉高等学校<br>正門・事務室</div></div></section><section><h2>校内の案内</h2><p>正門から中庭を通って教室棟へ。図書館は教室棟1階、理科実験室と美術室は2階、音楽室は3階です。体育館へは中庭の渡り廊下をお進みください。来校時は事務室で受付をお願いします。</p></section><section class="faq"><div class="eyebrow">FREQUENTLY ASKED QUESTIONS</div><h2>よくあるご質問</h2>${faqs.map(x=>`<details><summary>${x[0]}</summary><p>${x[1]}</p></details>`).join('')}</section>`)}
function field(label,name,type='text',required=true,value=''){return `<div class="field"><label for="f-${name}">${label}${required?'<span class="required">必須</span>':''}</label><input id="f-${name}" name="${name}" type="${type}" ${required?'required':''} value="${esc(value)}" maxlength="160" ${name==='email'?'autocomplete="email"':name==='name'?'autocomplete="name"':''}></div>`}
function formPage(kind,selection){const booking=kind==='reservation',v=draft?.kind===kind?draft.values:{};const selected=v.date??dates[Number(selection)||0];return titlePage(kind,`<div class="form-shell"><ol class="steps"><li class="current">1 入力</li><li>2 確認</li><li>3 完了</li></ol><p class="form-note">こちらはデモフォームです。実際の${booking?'予約登録':'送信・資料発送'}は行いません。テスト用の情報で操作できます。</p><form id="inquiry-form" data-kind="${kind}">${booking?`<div class="field"><label for="f-date">参加日程<span class="required">必須</span></label><select name="date" id="f-date" required>${dates.map(d=>`<option ${selected===d?'selected':''}>${d}</option>`).join('')}</select></div>`:`<div class="field"><label for="f-type">お問い合わせの種類<span class="required">必須</span></label><select id="f-type" name="type">${['資料請求','入試について','学校生活について','その他'].map(d=>`<option ${v.type===d?'selected':''}>${d}</option>`).join('')}</select></div>`}${field('お名前','name','text',true,v.name)}${field('メールアドレス','email','email',true,v.email)}${field('中学校名','school','text',false,v.school)}${booking?`<div class="field"><label for="f-people">参加人数（保護者を含む）<span class="required">必須</span></label><select name="people" id="f-people">${[1,2,3,4].map(n=>`<option ${String(v.people)===n+'名'?'selected':''}>${n}名</option>`).join('')}</select></div>`:''}<div class="field"><label for="f-message">${booking?'ご相談・配慮が必要なこと':'お問い合わせ内容'}</label><textarea name="message" id="f-message" maxlength="2000">${esc(v.message)}</textarea></div>${!booking?'<p class="fine">学校案内は完了画面から閲覧・印刷できます。住所の入力や実際の郵送はありません。</p>':''}<label class="check"><input name="consent" type="checkbox" required ${v.consent?'checked':''}><span><a href="#privacy">プライバシーポリシー</a>を確認し、デモであることに同意します。</span></label><button class="button" type="submit">入力内容を確認する <span>→</span></button></form></div>`)}
function confirmation(){const d=draft;if(!d){location.hash='contact';return ''}const names={date:'参加日程',type:'種別',name:'お名前',email:'メールアドレス',school:'中学校名',people:'参加人数',message:'お問い合わせ・ご相談'};return titlePage(d.kind,`<div class="form-shell"><ol class="steps"><li>1 入力</li><li class="current">2 確認</li><li>3 完了</li></ol><h2>入力内容をご確認ください</h2><dl class="info">${Object.entries(d.values).filter(([k])=>k!=='consent').map(([k,v])=>`<dt>${names[k]||k}</dt><dd style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(v||'未入力')}</dd>`).join('')}</dl><p class="form-note" style="margin-top:25px">完了しても外部には送信されません。</p><div class="actions"><button class="button outline" id="form-back">入力内容を修正する</button><button class="button" id="form-complete">デモを完了する →</button></div></div>`)}
function complete(){const booking=draft?.kind==='reservation';draft=null;return titlePage(booking?'reservation':'contact',`<div class="form-shell"><ol class="steps"><li>1 入力</li><li>2 確認</li><li class="current">3 完了</li></ol><div class="success"><div class="success-mark">✓</div><h2>デモ受付が完了しました</h2><p>ご入力ありがとうございました。<br>実際の送信・予約・資料発送は行っていません。<br>入力した個人情報は保存されません。</p><div class="actions" style="justify-content:center"><a class="button" href="guide.html" target="_blank">学校案内を読む ↗</a>${link('home','ホームに戻る','button outline')}</div></div></div>`)}
function infoPage(key){const content={students:`<section><h2>今月の主な予定</h2><dl class="info"><dt>9月7日</dt><dd>2学期通常授業</dd><dt>9月14日</dt><dd>防災訓練・委員会活動</dd><dt>9月26日</dt><dd>オープンキャンパス（案内係生徒は9:00集合）</dd></dl></section><section><h2>欠席・遅刻の連絡</h2><p>8:20までに担任への連絡をお願いします。このデモには実際の連絡システムや電話窓口は接続していません。</p><h2>各種手続き</h2><p>住所変更、通学経路変更、生徒証の再発行は、事務室で申請書を受け取る想定です。受付は平日9:00–16:30です。</p>${link('news','学校のお知らせを確認する')}</section>`,graduates:`<section><h2>証明書の発行</h2><p>卒業証明書、成績証明書、調査書などの申請方法をご案内します。本人確認書類と卒業年度の確認が必要です。</p><dl class="info"><dt>卒業証明書</dt><dd>発行目安：受付から3営業日</dd><dt>成績証明書</dt><dd>発行目安：受付から5営業日。保存期間により発行できない場合があります。</dd><dt>申請窓口</dt><dd>学校事務室。事前にお問い合わせフォームで種類をご相談ください。</dd></dl><p class="fine">このデモでは実際の発行申請はできません。</p>${link('contact','お問い合わせへ','button')}</section><section><h2>同窓会からのお知らせ</h2><p>2026年度の同窓会は11月21日、青葉会館での開催を想定しています。恩師や旧友と近況を語り合う機会です。詳細は10月に掲載予定です。</p></section>`,privacy:`<section><h2>デモサイトについて</h2><p>本サイトは架空の学校の制作見本です。フォームの内容は画面表示のためにブラウザのメモリ内で一時的に扱い、外部のサーバーへ送信しません。入力内容は完了時またはページ再読み込み時に消去されます。</p><h2>保存と計測</h2><p>フォーム内容をCookieやローカルストレージへ保存しません。アクセス解析サービスや広告トラッキングも組み込んでいません。</p><h2>画像と外部リンク</h2><p>写真は共通のローカル素材から読み込みます。写真の出典や学校案内へのリンクがあります。外部リンク先の情報の取り扱いは各サイトの方針に従います。</p><h2>連絡について</h2><p>このページ内の学校名・住所・人物は架空です。実在校へのお問い合わせや入試出願の窓口ではありません。</p></section>`,sitemap:`<div class="sitemap">${Object.entries(routeInfo).filter(([k])=>k!=='sitemap').map(([k,v])=>link(k,v[0])).join('')}<a href="guide.html">学校案内（印刷用） ↗</a></div>`};return titlePage(key,content[key])}
function missing(){return `<div class="wrap section"><h1>ページが見つかりません</h1><p>リンクをご確認いただくか、ホームからお探しください。</p>${link('home','ホームへ','button')}</div>`}
function route(){const [key='home',sub]=(location.hash.slice(1)||'home').split('/');$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');if($('#search-dialog').open)$('#search-dialog').close();document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+key));let html;switch(key){case'home':html=home();break;case'about':html=about();break;case'learning':html=learning();break;case'life':html=life();break;case'clubs':html=clubPage(sub);break;case'admissions':html=admissions();break;case'news':html=newsPage(sub);break;case'access':html=access();break;case'contact':case'reservation':html=formPage(key,sub);break;case'confirm':html=confirmation();break;case'complete':html=complete();break;default:html=routeInfo[key]?infoPage(key):missing()}main.innerHTML=html;document.title=(routeInfo[key]?.[0]||'受付')+' | 私立 青葉高等学校';window.scrollTo(0,0);main.focus({preventScroll:true});}
window.addEventListener('hashchange',route);
$('#menu-toggle').addEventListener('click',()=>{const open=$('#navigation').classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open))});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#navigation').classList.contains('open')){$('#navigation').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');$('#menu-toggle').focus()}});
$('#search-toggle').addEventListener('click',()=>{$('#search-dialog').showModal();$('#site-query').focus()});$('#search-close').addEventListener('click',()=>$('#search-dialog').close());
const searchable=()=>[...Object.entries(routeInfo).map(([k,v])=>({href:k,title:v[0],text:v[2]})),...news.map((n,i)=>({href:'news/'+i,title:n[2],text:n[3]+' '+n[4]})),...clubs.map(c=>({href:'clubs/'+c[0],title:c[1],text:c[4]+' '+c[5]+' '+c[7]})),{href:'life',title:'図書館・学校施設',text:'図書館 教室 理科実験室 体育館 ラーニングコモンズ 中庭 自習 年間行事'},{href:'admissions',title:'募集要項・学費',text:'入学金 授業料 学費 費用 800000 2027 募集 試験 推薦 一般 入試'}];
$('#search-form').addEventListener('submit',e=>{e.preventDefault();const q=$('#site-query').value.trim().toLocaleLowerCase();const hits=q?searchable().filter(x=>(x.title+' '+x.text).toLocaleLowerCase().includes(q)):[];$('#search-results').innerHTML=`<p class="fine" style="margin-top:25px">「${esc(q)}」の検索結果：${hits.length}件</p>`+(hits.length?hits.map(x=>`<a class="result" href="#${x.href}"><strong>${x.title} →</strong><small>${esc(x.text.slice(0,95))}…</small></a>`).join(''):'<p class="empty">該当するページがありません。別のキーワードでお試しください。</p>')});
$('#search-results').addEventListener('click',e=>{if(e.target.closest('a'))$('#search-dialog').close()});
main.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(b){const kind=b.dataset.filter,value=b.dataset.value;b.parentElement.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(kind==='clubs'){clubFilter=value;$('#club-list').innerHTML=clubCards()}else if(kind==='news'){newsFilter=value;$('#news-list').innerHTML=newsRows(news.filter(n=>value==='すべて'||n[1]===value))}else{$('#home-news').innerHTML=newsRows(news.filter(n=>value==='すべて'||n[1]===value).slice(0,4))}}if(e.target.closest('#form-back')&&draft)location.hash=draft.kind;if(e.target.closest('#form-complete'))location.hash='complete'});
main.addEventListener('submit',e=>{if(e.target.id!=='inquiry-form')return;e.preventDefault();const form=e.target;const name=form.elements.name;if(!name.value.trim()){name.setCustomValidity('お名前を入力してください。');name.reportValidity();return}name.setCustomValidity('');draft={kind:form.dataset.kind,values:Object.fromEntries(new FormData(form))};location.hash='confirm'});
main.addEventListener('input',e=>{if(e.target.name==='name')e.target.setCustomValidity('');const f=e.target.closest('#inquiry-form');if(f)draft={kind:f.dataset.kind,values:Object.fromEntries(new FormData(f))}});
route();
