'use strict';
(() => {
const BASE='../experiments/social-game/';
const KEY='ui-lab:game-astra-solo-01:v1';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const unique=xs=>[...new Set(xs)];
const uid=()=>crypto.randomUUID();
let data,state,temporary=false,team=[],draft={category:'質問',title:'',author:'',body:''},timer;
const blank=()=>({version:1,owner:uid(),bookmarks:[],threads:[],replies:{},edits:{},deleted:[]});
const validPost=p=>p&&typeof p.id==='string'&&typeof p.author==='string'&&typeof p.body==='string'&&typeof p.owner==='string'&&typeof p.created==='string';
function validState(s){return s&&s.version===1&&typeof s.owner==='string'&&Array.isArray(s.bookmarks)&&s.bookmarks.every(x=>typeof x==='string')&&Array.isArray(s.threads)&&s.threads.every(p=>validPost(p)&&typeof p.title==='string'&&['質問','攻略共有','雑談'].includes(p.category)&&(p.replies===undefined||(Array.isArray(p.replies)&&p.replies.every(validPost))))&&s.replies&&typeof s.replies==='object'&&!Array.isArray(s.replies)&&Object.values(s.replies).every(a=>Array.isArray(a)&&a.every(validPost))&&s.edits&&typeof s.edits==='object'&&!Array.isArray(s.edits)&&Object.values(s.edits).every(p=>p&&typeof p.body==='string'&&(p.title===undefined||typeof p.title==='string'))&&Array.isArray(s.deleted)&&s.deleted.every(x=>typeof x==='string');}
function storageWarning(message){temporary=true;$('#storage-warning').hidden=false;$('#storage-warning').innerHTML=esc(message)+' この画面では一時利用できます。再読込すると変更は失われます。 <a href="#privacy">データ管理・復旧</a>';}
function readState(){state=blank();try{const raw=localStorage.getItem(KEY);if(raw){const s=JSON.parse(raw);if(!validState(s))throw Error('invalid');state=s;}}catch{storageWarning('保存データを読み込めません。破損または保存先の利用制限があります。');}}
function save(){if(temporary)return false;try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{storageWarning('保存に失敗しました。保存先の空き容量やブラウザ設定を確認してください。');return false;}}
function notice(text){$('#toast').textContent=text;clearTimeout(timer);timer=setTimeout(()=>$('#toast').textContent='',6000);}
function changed(message){const persisted=save();notice(persisted?message+'（このブラウザに保存）':message+'（一時利用・未保存）');}
const image=(p,cls='')=>`<img class="${cls}" src="${BASE+esc(p.image)}" alt="${esc(p.name||p.title)}" loading="lazy">`;
const link=(route,label,cls='')=>`<a class="${cls}" href="#${route}">${esc(label)}</a>`;
const badge=s=>`<span class="badge">${esc(s)}</span>`;
const character=id=>data.characters.find(c=>c.id===id);
const breadcrumb=(name,route='home',parent='トップ')=>`<div class="breadcrumbs">${link(route,parent)}<span aria-hidden="true">/</span><span>${esc(name)}</span></div>`;
const title=(heading,description='',eyebrow='FIELD NOTES')=>`<div class="intro"><div><div class="eyebrow">${eyebrow}</div><h1 class="page-title" tabindex="-1">${esc(heading)}</h1>${description?`<p class="muted">${esc(description)}</p>`:''}</div></div>`;
const empty=(text='条件に合う情報が見つかりません。')=>`<div class="empty"><h2>0件です</h2><p>${esc(text)}</p></div>`;
function select(name,label,values,current='',all='すべて'){return `<label>${esc(label)}<select name="${name}" aria-label="${esc(label)}">${all!==null?`<option value="">${all}</option>`:''}${values.map(v=>{const [value,text]=Array.isArray(v)?v:[v,v];return `<option value="${esc(value)}" ${value===current?'selected':''}>${esc(text)}</option>`;}).join('')}</select></label>`;}
function charCard(c,add=false){return `<div class="character-card" data-character="${c.id}"><a href="#character/${c.id}">${image(c)}<div class="character-info"><h3>${esc(c.name)}<span class="rating">${c.rating.toFixed(1)}</span></h3><div class="meta">${esc(c.rarity)} · ${esc(c.element)}属性 · ${esc(c.role)}</div></div></a>${add?`<button data-add="${c.id}" aria-label="${esc(c.name)}を編成に追加">＋ 編成に追加</button>`:''}</div>`;}
function related(ids){return `<div class="related">${ids.map(character).filter(Boolean).map(c=>`<a href="#character/${c.id}">${image(c)}<span>${esc(c.name)}<small> / ${esc(c.role)}</small></span></a>`).join('')}</div>`;}
function guideRow(g){return `<a class="guide-row" href="#guide/${g.id}" data-guide="${g.id}"><div class="row-content">${badge(g.category)}<h3>${esc(g.title)}</h3><p>対象：${g.characters.map(id=>esc(character(id).name)).join('・')}</p></div><span class="meta date">${g.updated}</span><span class="arrow" aria-hidden="true">↗</span></a>`;}
function threads(){return [...data.threads,...state.threads].filter(t=>!state.deleted.includes(t.id)).map(t=>{const own=t.owner===state.owner;return {...t,...(own?state.edits[t.id]:{}),replies:[...(t.replies||[]),...(state.replies[t.id]||[])].filter(p=>!state.deleted.includes(p.id)).map(p=>({...p,...(p.owner===state.owner?state.edits[p.id]:{})}))};});}
function threadRow(t){return `<a class="thread-row" href="#thread/${esc(t.id)}" data-thread="${esc(t.id)}"><div class="row-content">${badge(t.category)}<h3>${esc(t.title)}</h3><span class="meta">${esc(t.author)} · ${esc(t.created.slice(0,10))}</span></div><div class="reply-count">${t.replies.length}<small>返信</small></div><span class="arrow" aria-hidden="true">›</span></a>`;}
function home(){return `${title('次の冒険に、確かな道しるべ。','育成のヒントから仲間との相談まで。星環クロニクルの攻略情報をひとつに。','SEIKAN CHRONICLE / PLAYER’S GUIDE')}<a class="mobile-start" href="#guide/g01"><span>はじめての旅人へ</span><strong>最初の3日ガイド →</strong></a><div class="layout"><div><section class="panel"><div class="section-head"><h2><span class="section-no">01</span>開催中のイベント</h2><span class="meta">全3件</span></div><div class="event-grid">${data.events.map(e=>`<a class="event-card" href="#event/${e.id}">${image(e)}<div>${badge(e.status)}<h3>${esc(e.title)}</h3><div class="meta">9/1 – 9/21 · 報酬・攻略を見る ↗</div></div></a>`).join('')}</div></section><section class="panel"><div class="section-head"><h2><span class="section-no">02</span>最新の攻略・更新情報</h2>${link('guides','全8記事を見る →')}</div><p class="meta">2026.09.07 更新 · 育成と編成の基本をチェック</p>${data.guides.slice(0,4).map(guideRow).join('')}</section><section class="panel"><div class="section-head"><h2><span class="section-no">03</span>旅人たちの相談室</h2>${link('board','掲示板へ →')}</div>${threads().slice(0,3).map(threadRow).join('')}</section></div><aside><section class="panel beginner"><div class="eyebrow">START HERE</div><h2>はじめての旅人へ</h2><p class="muted">最初の3日で、何をする？<br>育成と進行の順番を整理しよう。</p>${link('guide/g01','初心者ガイドを読む →','button')}</section><section class="panel"><h2>攻略を探す</h2><div class="quicklinks">${link('characters','キャラ図鑑　12体 →')}${link('team','4人の編成を組む →')}${link('guides?category=育成','育成・素材を調べる →')}${link('new','質問を投稿する →')}</div></section><div class="note"><strong>この攻略室について</strong><p>架空ゲームのローカルデモです。日程・開催状態は固定データに基づきます。</p><small>情報基準：2026.09.07</small></div></aside></div>`;}
function characters(params){const q=params.get('q')||'',element=params.get('element')||'',role=params.get('role')||'',rarity=params.get('rarity')||'',sort=params.get('sort')||'rating';let list=data.characters.filter(c=>c.name.includes(q)&&(!element||c.element===element)&&(!role||c.role===role)&&(!rarity||c.rarity===rarity));list.sort(sort==='name'?(a,b)=>a.name.localeCompare(b.name,'ja'):(a,b)=>b.rating-a.rating);return `${breadcrumb('キャラ図鑑')}${title('キャラ図鑑','属性と役割を見比べて、冒険の仲間を見つけよう。','CHARACTER ARCHIVE')}<form class="filters" data-route="characters"><label class="wide">キャラ名<input name="q" value="${esc(q)}" placeholder="名前で検索"></label>${select('element','属性',['火','水','風','光'],element)}${select('role','役割',['攻撃','支援','防御'],role)}${select('rarity','レア度',['SSR','SR'],rarity)}${select('sort','並べ替え',[['rating','評価の高い順'],['name','名前順']],sort,null)}<button>絞り込む</button>${link('characters','リセット','button secondary')}</form><div class="result-bar"><strong id="result-count">${list.length}体 / 全12体</strong><span class="meta">評価は実験用の固定値です</span></div>${list.length?`<div class="character-grid">${list.map(c=>charCard(c)).join('')}</div>`:empty('キャラ名や絞り込み条件を変更してください。')}`;}
function characterDetail(c){return `${breadcrumb(c.name,'characters','キャラ図鑑')}${title(c.name,`${c.rarity} / ${c.element}属性 / ${c.role}`,'CHARACTER PROFILE')}<div class="panel character-detail">${image(c,'portrait')}<div>${badge(c.role)}<dl class="stats"><div><dt>評価</dt><dd><strong>${c.rating.toFixed(1)}</strong></dd></div><div><dt>攻撃力</dt><dd><strong>${c.attack}</strong></dd></div><div><dt>HP</dt><dd><strong>${c.hp}</strong></dd></div></dl><h2>スキル</h2><p>${esc(c.skill)}</p><h2>育成素材</h2><ul>${c.materials.map(m=>`<li>${esc(m)}</li>`).join('')}</ul><div class="actions"><button data-add="${c.id}">＋ 編成に追加</button>${link('team','編成ツールを見る','button secondary')}</div></div></div><section class="panel"><h2>相性のよい仲間</h2>${related(c.partners)}</section>`;}
function guides(params,saved=false){const category=params.get('category')||'';const list=data.guides.filter(g=>(!saved||state.bookmarks.includes(g.id))&&(!category||g.category===category));return `${breadcrumb(saved?'保存した記事':'攻略記事')}${title(saved?'保存した記事':'攻略記事',saved?'あとで読みたい攻略を、このブラウザに。':'育成・ボス・編成。知りたいことから攻略を探そう。','STRATEGY LIBRARY')}${saved?'':`<form class="filters" data-route="guides">${select('category','カテゴリ',unique(data.guides.map(g=>g.category)),category)}<button>絞り込む</button>${link('guides','リセット','button secondary')}</form>`}<p id="result-count">${list.length}記事</p>${list.length?`<div class="panel">${list.map(guideRow).join('')}</div>`:empty('記事ページの「保存する」から追加できます。')}`;}
function guideDetail(g){const saved=state.bookmarks.includes(g.id);return `${breadcrumb(g.title,'guides','攻略記事')}<div class="layout"><article class="panel article">${badge(g.category)}${title(g.title,'','STRATEGY GUIDE')}<p class="meta">更新：${g.updated}</p><p>${esc(g.summary)}</p><button class="secondary" data-bookmark="${g.id}" aria-pressed="${saved}">${saved?'✓ 保存済み・解除する':'＋ 記事を保存する'}</button><nav class="toc" aria-label="記事の目次"><h2>目次</h2>${g.sections.map((s,i)=>`<a href="#guide/${g.id}?section=${i}">${i+1}. ${esc(s.heading)}</a>`).join('')}</nav>${g.sections.map((s,i)=>`<section id="section-${i}" tabindex="-1"><h2>${esc(s.heading)}</h2><p>${esc(s.body)}</p></section>`).join('')}<section><h2>関連キャラ</h2>${related(g.characters)}</section></article><aside><section class="panel"><h2>攻略を実践する</h2><p class="muted">役割を確認して、自分の4人を組んでみよう。</p>${link('team','編成ツールへ →','button')}</section><section class="panel"><h2>解決しなかったら</h2><p class="muted">旅人たちに編成や攻略を相談できます。</p>${link('board','掲示板で相談する →')}</section></aside></div>`;}
function eventDetail(e){return `${breadcrumb(e.title)}${title(e.title,'期間限定の探索イベント','EVENT GUIDE')}<div class="layout"><article class="panel">${image(e,'hero-event')}${badge(e.status)}<p>開催期間：${e.start} 〜 ${e.end}</p><h2>攻略ポイント</h2><p>${esc(e.description)}</p><h2>主な報酬</h2><ul>${e.rewards.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><h2>関連記事</h2>${guideRow(data.guides.find(g=>g.id===e.guide))}</article><aside><div class="note">開催状態は2026年9月7日の固定データです。実際のゲームイベントではありません。</div></aside></div>`;}
function teamPage(params){let warning='';if(params.has('ids')){const ids=(params.get('ids')||'').split(',').filter(Boolean);team=unique(ids.filter(id=>character(id))).slice(0,4);if(team.length!==ids.length)warning='不正なID・重複ID・5枠目以降を除外しました。';}const url=location.href.split('#')[0]+'#team?ids='+team.join(',');return `${breadcrumb('編成ツール')}${title('4人で、ひとつの星環を。','仲間を選んで編成し、URLで組み合わせを共有できます。','PARTY BUILDER')}${warning?`<div role="status" class="note">${warning}</div>`:''}<div class="result-bar"><strong>${team.length} / 4枠を編成中</strong><span class="meta">同じキャラは1体まで</span></div><div class="team-slots">${Array.from({length:4},(_,i)=>{const c=character(team[i]);return `<div class="slot"><span class="slot-number">SLOT 0${i+1}</span>${c?`${image(c)}<strong>${esc(c.name)}</strong><span class="meta">${c.element} · ${c.role}</span><button class="secondary" data-remove="${c.id}" aria-label="${esc(c.name)}を編成から外す">外す</button>`:'<strong>＋ 仲間を選ぶ</strong><span class="meta">下の一覧から追加</span>'}</div>`;}).join('')}</div><section class="panel share-box"><label for="share-url">編成の共有URL（選択して手動コピーもできます）<input id="share-url" readonly value="${esc(url)}"></label><button data-copy>URLをコピー</button></section><div class="section-head"><h2>仲間を追加する</h2>${link('characters','能力を詳しく見る →')}</div><div class="character-grid">${data.characters.map(c=>charCard(c,true)).join('')}</div>`;}
function board(params){const category=params.get('category')||'',q=params.get('q')||'',sort=params.get('sort')||'new';const list=threads().filter(t=>(!category||t.category===category)&&[t.title,t.body,...t.replies.map(p=>p.body)].join(' ').includes(q));list.sort(sort==='replies'?(a,b)=>b.replies.length-a.replies.length:(a,b)=>b.created.localeCompare(a.created));return `${breadcrumb('掲示板')}${title('旅人たちの掲示板','攻略の疑問も、今日の冒険も。気軽に話してみよう。','COMMUNITY')}<div class="result-bar"><span class="meta">このブラウザ内のデモ掲示板です</span>${link('new','＋ スレッドを作成','button')}</div><form class="filters" data-route="board">${select('category','カテゴリ',['質問','攻略共有','雑談'],category)}<label class="wide">スレッド検索<input name="q" value="${esc(q)}" placeholder="タイトル・本文で検索"></label>${select('sort','並べ替え',[['new','新着順'],['replies','返信数順']],sort,null)}<button>絞り込む</button>${link('board','リセット','button secondary')}</form><p id="result-count">${list.length}スレッド · ${list.reduce((n,t)=>n+1+t.replies.length,0)}投稿（親投稿を含む）</p>${list.length?`<div class="panel">${list.map(threadRow).join('')}</div>`:empty()}<p class="meta">投稿前に ${link('rules','掲示板利用ルール')} をご確認ください。</p>`;}
function post(t,p,parent=false){const own=p.owner===state.owner;return `<article class="post" data-post="${esc(p.id)}"><div class="post-head"><strong>${esc(p.author)} ${own?badge('自分'):''}${parent?badge('親投稿'):''}</strong><time class="meta">${esc(p.created.replace('T',' ').replace('Z',' UTC'))}</time></div><p class="post-body">${esc(p.body)}</p><div class="actions">${own?`<button data-edit="${esc(p.id)}" data-thread-id="${esc(t.id)}">編集</button><button data-delete="${esc(p.id)}" data-thread-id="${esc(t.id)}">削除</button>`:`<button data-report="${esc(p.id)}">通報デモ</button>`}</div></article>`;}
function threadDetail(t){return `${breadcrumb(t.title,'board','掲示板')}${badge(t.category)}${title(t.title,'','THREAD')}<div class="layout"><div>${post(t,t,true)}<div class="section-head"><h2>返信 <span id="reply-count">${t.replies.length}</span>件</h2></div>${t.replies.map(p=>post(t,p)).join('')}${!t.replies.length?'<p class="muted">まだ返信はありません。最初のひと言をどうぞ。</p>':''}<section class="panel"><h2>返信を書く</h2><form id="reply-form" class="form-stack" data-thread-id="${esc(t.id)}" novalidate><label for="reply-author">表示名</label><input id="reply-author" name="author" aria-describedby="reply-author-help"><small id="reply-author-help">24文字以内。空欄の場合は「名無しの旅人」</small><label for="reply-body">本文（必須）</label><textarea id="reply-body" name="body" aria-describedby="reply-help"></textarea><small id="reply-help">1〜1000文字。空白のみは投稿できません。</small><div class="error" role="alert"></div><div class="actions"><button>返信を投稿する</button></div></form></section></div><aside><section class="panel"><h2>気持ちよく話すために</h2><p class="muted">個人情報を含めず、互いを尊重した言葉で投稿しましょう。</p>${link('rules','利用ルールを読む →')}</section></aside></div>`;}
function newForm(confirming=false){return `${breadcrumb('スレッド作成','board','掲示板')}${title(confirming?'投稿内容を確認':'スレッドを作成','投稿はこのブラウザ内にだけ保存され、外部には送信されません。','NEW THREAD / '+(confirming?'02 CONFIRM':'01 WRITE'))}<section class="panel form-stack">${confirming?`<dl class="confirm-data"><dt>カテゴリ</dt><dd>${esc(draft.category)}</dd><dt>タイトル</dt><dd>${esc(draft.title)}</dd><dt>表示名</dt><dd>${esc(draft.author)}</dd><dt>本文</dt><dd>${esc(draft.body)}</dd></dl><div class="actions"><button id="publish-thread">この内容で投稿する</button><button class="secondary" id="revise-thread">修正する</button></div>`:`<form id="new-thread" novalidate>${select('category','カテゴリ',['質問','攻略共有','雑談'],draft.category,null)}<label for="new-title">タイトル（必須）</label><input id="new-title" name="title" value="${esc(draft.title)}" aria-describedby="title-help"><small id="title-help">1〜80文字</small><label for="new-author">表示名（必須）</label><input id="new-author" name="author" value="${esc(draft.author)}" aria-describedby="author-help"><small id="author-help">1〜24文字</small><label for="new-body">本文（必須）</label><textarea id="new-body" name="body" aria-describedby="body-help">${esc(draft.body)}</textarea><small id="body-help">1〜1000文字。空白のみは無効です。HTMLは文字として表示されます。</small><div class="error" role="alert"></div><div class="actions"><button>確認へ進む</button>${link('board','掲示板に戻る','button secondary')}</div></form>`}</section>`;}
function search(params){const q=(params.get('q')||'').trim(),type=params.get('type')||'';const groups=[['character','キャラ',data.characters.map(c=>({id:c.id,title:c.name,body:[c.skill,...c.materials,c.element,c.role].join(' ')}))],['guide','攻略',data.guides.map(g=>({id:g.id,title:g.title,body:g.summary+' '+g.sections.map(s=>s.heading+' '+s.body).join(' ')}))],['thread','スレッド',threads().map(t=>({id:t.id,title:t.title,body:[t.body,...t.replies.map(p=>p.body)].join(' ')}))]];const results=groups.flatMap(([kind,label,items])=>(!type||type===kind)?items.filter(p=>q&&(p.title+' '+p.body).toLocaleLowerCase().includes(q.toLocaleLowerCase())).map(p=>({...p,kind,label})):[]);return `${breadcrumb('検索')}${title('サイト内検索','キャラ・攻略記事・スレッドのタイトルと本文を横断検索。','SEARCH')}<form class="filters" data-route="search"><label class="wide">検索語<input name="q" value="${esc(q)}"></label>${select('type','種別',[['character','キャラ'],['guide','攻略'],['thread','スレッド']],type)}<button>検索する</button></form><p id="result-count">「${esc(q)}」 / ${type?esc(groups.find(g=>g[0]===type)?.[1]||type):'すべての種別'}：${results.length}件</p>${results.length?`<section class="panel">${results.map(r=>`<a class="guide-row" href="#${r.kind}/${esc(r.id)}"><div class="row-content">${badge(r.label)}<h3>${esc(r.title)}</h3><p>${esc(r.body.slice(0,110))}…</p></div><span class="arrow">↗</span></a>`).join('')}</section>`:empty(q?'別の検索語を試してください。':'検索語を入力してください。')}`;}
function info(route){if(route==='rules')return `${breadcrumb('掲示板利用ルール')}${title('掲示板利用ルール')}<article class="panel article"><h2>旅人同士を尊重しましょう</h2><p>誹謗中傷、差別、迷惑行為、広告・勧誘は控えてください。ゲームの楽しみ方の違いを尊重してください。</p><h2>個人情報を書かない</h2><p>本名、住所、連絡先、パスワードなどは投稿しないでください。ネタバレを含む場合はタイトルで知らせましょう。</p><h2>投稿の管理</h2><p>このデモでは自分の投稿を編集・削除できます。他人の投稿の通報は操作体験のみで、実際の送信や削除は行いません。</p>${link('board','掲示板に戻る','button secondary')}</article>`;if(route==='credits')return `${breadcrumb('素材出典')}${title('素材出典')}<article class="panel article"><p>キャラ12体・イベント3件のSVGは、この実験用に作成された共通素材です。</p><p>データ：experiments/social-game/fixtures/content.json<br>画像：experiments/social-game/assets/</p><p>外部画像・外部フォント・画像生成サービスは使用していません。実在するゲーム・運営とは無関係です。</p></article>`;return `${breadcrumb('プライバシー・データ管理')}${title('プライバシー・データ管理')}<article class="panel article"><h2>このブラウザだけの保存</h2><p>投稿、返信、編集、削除、保存した記事を専用のlocalStorageキーに記録します。ログイン、実認証、外部送信、実際の投稿共有はありません。</p><p>自分の投稿はローカルの所有者IDで判定します。ブラウザや保存データが異なる場合、同じ利用者として扱われません。</p><h2>保存できないとき</h2><p>一時利用中の変更は再読込で失われます。ブラウザの保存許可・空き容量を確認してください。破損したデータは下の初期化で復旧できます。</p><div class="danger-zone"><h2>デモデータの初期化</h2><p>このデモの投稿・返信・保存一覧を削除して、固定データに戻します。他サイトの保存キーは削除しません。取り消しできないため、必要な投稿は事前に控えてください。</p><button class="danger" id="reset-data">デモデータを初期化</button></div></article>`;}
function missing(){return `${breadcrumb('見つかりません')}${title('ページが見つかりません','URLのIDが存在しないか、投稿が削除されています。')}${link('home','トップへ戻る','button')}`;}
function render(focus=true){const [path,query='']=(location.hash.slice(1)||'home').split('?');const [route,id]=path.split('/');const params=new URLSearchParams(query);let html;const t=()=>threads().find(t=>t.id===id);switch(route){case'home':html=home();break;case'characters':html=characters(params);break;case'character':html=character(id)?characterDetail(character(id)):missing();break;case'guides':html=guides(params);break;case'saved':html=guides(params,true);break;case'guide':html=data.guides.some(g=>g.id===id)?guideDetail(data.guides.find(g=>g.id===id)):missing();break;case'event':html=data.events.some(e=>e.id===id)?eventDetail(data.events.find(e=>e.id===id)):missing();break;case'team':html=teamPage(params);break;case'board':html=board(params);break;case'thread':html=t()?threadDetail(t()):missing();break;case'new':html=newForm();break;case'search':html=search(params);break;case'rules':case'privacy':case'credits':html=info(route);break;default:html=missing();}$('#main').innerHTML=html;closeMenu();const navRoute={character:'characters',guide:'guides',thread:'board',new:'board'}[route]||route;$('#primary-nav').querySelectorAll('a').forEach(a=>{if(a.hash==='#'+navRoute)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.title=($('.page-title')?.textContent||'攻略室')+' | 星環クロニクル攻略室';if(focus){$('.page-title')?.focus();window.scrollTo(0,0);}if(route==='guide'&&params.has('section')){const section=document.getElementById('section-'+params.get('section'));section?.scrollIntoView();section?.focus();}}
function go(route){if(location.hash==='#'+route)render();else location.hash=route;}
function closeMenu(){$('#primary-nav').classList.remove('open');$('#menu-toggle').setAttribute('aria-expanded','false');}
function modal(heading,body,onConfirm,confirmText='確定する'){const d=$('#modal');d.innerHTML=`<h2 id="modal-title">${esc(heading)}</h2>${body}<div class="actions"><button id="modal-confirm">${esc(confirmText)}</button><button class="secondary" id="modal-cancel">取消</button></div>`;$('#modal-cancel').onclick=()=>d.close();$('#modal-confirm').onclick=()=>onConfirm(d);d.showModal();$('#modal-cancel').focus();}
function validation(values,thread=false){const errors=[];if(thread&&(!values.title.trim()||values.title.trim().length>80))errors.push('タイトルは空白以外の1〜80文字で入力してください。');if((thread&&!values.author.trim())||values.author.trim().length>24)errors.push('表示名は'+(thread?'1〜24':'24')+'文字以内で入力してください。');if(!values.body.trim()||values.body.trim().length>1000)errors.push('本文は空白以外の1〜1000文字で入力してください。');return errors;}
function formErrors(form,errors){const box=form.querySelector('.error');box.textContent=errors.join(' ');if(errors.length){box.setAttribute('tabindex','-1');box.focus();return true;}return false;}
document.addEventListener('submit',event=>{const form=event.target;event.preventDefault();if(form.id==='global-search'){go('search?q='+encodeURIComponent(new FormData(form).get('q').trim()));return;}if(form.dataset.route){go(form.dataset.route+'?'+new URLSearchParams(new FormData(form)).toString());return;}if(form.id==='new-thread'){draft=Object.fromEntries(new FormData(form));if(formErrors(form,validation(draft,true)))return;$('#main').innerHTML=newForm(true);$('.page-title').focus();window.scrollTo(0,0);}if(form.id==='reply-form'){const values=Object.fromEntries(new FormData(form));if(formErrors(form,validation(values)))return;const id=form.dataset.threadId;state.replies[id]??=[];state.replies[id].push({id:uid(),author:values.author.trim()||'名無しの旅人',body:values.body.trim(),owner:state.owner,created:new Date().toISOString()});changed('返信を追加しました');render(false);}});
document.addEventListener('input',e=>{if(e.target.form?.id==='new-thread')draft=Object.fromEntries(new FormData(e.target.form));});
document.addEventListener('click',async event=>{const b=event.target.closest('button');if(!b)return;if(b.id==='menu-toggle'){const open=b.getAttribute('aria-expanded')!=='true';$('#primary-nav').classList.toggle('open',open);b.setAttribute('aria-expanded',String(open));return;}
if(b.dataset.add){const id=b.dataset.add;if(team.includes(id)){notice('このキャラはすでに編成されています。重複して追加できません。');return;}if(team.length>=4){notice('編成は4枠で満員です。1人外してから追加してください。');return;}team.push(id);notice(character(id).name+'を編成に追加しました');if(location.hash.startsWith('#team'))go('team?ids='+team.join(','));return;}
if(b.dataset.remove){team=team.filter(id=>id!==b.dataset.remove);go('team?ids='+team.join(','));notice('編成から外しました');return;}
if(b.hasAttribute('data-copy')){const input=$('#share-url');try{await navigator.clipboard.writeText(input.value);notice('編成URLをコピーしました');}catch{input.focus();input.select();notice('コピーできません。表示されたURLを選択して手動でコピーしてください。');}return;}
if(b.dataset.bookmark){const id=b.dataset.bookmark;const exists=state.bookmarks.includes(id);state.bookmarks=exists?state.bookmarks.filter(x=>x!==id):[...state.bookmarks,id];changed(exists?'保存を解除しました':'記事を保存しました');b.setAttribute('aria-pressed',String(!exists));b.textContent=!exists?'✓ 保存済み・解除する':'＋ 記事を保存する';return;}
if(b.id==='revise-thread'){$('#main').innerHTML=newForm();$('.page-title').focus();return;}
if(b.id==='publish-thread'){const errors=validation(draft,true);if(errors.length){notice(errors.join(' '));return;}const t={id:uid(),category:draft.category,title:draft.title.trim(),author:draft.author.trim(),body:draft.body.trim(),owner:state.owner,created:new Date().toISOString()};state.threads.push(t);changed('スレッドを投稿しました');draft={category:'質問',title:'',author:'',body:''};go('thread/'+t.id);return;}
if(b.dataset.edit||b.dataset.delete){const t=threads().find(t=>t.id===b.dataset.threadId);const id=b.dataset.edit||b.dataset.delete;const p=t?.id===id?t:t?.replies.find(p=>p.id===id);if(!p||p.owner!==state.owner)return;if(b.dataset.delete){modal('投稿を削除しますか？',`<p>${t.id===id?'このスレッドと返信を一覧から削除します。':'この返信を削除します。'}取消を選ぶと投稿は残ります。</p>`,d=>{state.deleted.push(id);changed('投稿を削除しました');d.close();if(t.id===id)go('board');else render(false);},'削除する');}else{modal('自分の投稿を編集',`${t.id===id?`<label for="edit-title">タイトル（1〜80文字）</label><input id="edit-title" value="${esc(t.title)}">`:''}<label for="edit-body">本文（1〜1000文字）</label><textarea id="edit-body">${esc(p.body)}</textarea><div class="error" role="alert"></div>`,d=>{const values={author:p.author,title:$('#edit-title')?.value||'',body:$('#edit-body').value};const errors=validation(values,t.id===id);if(formErrors(d,errors))return;state.edits[id]={body:values.body.trim(),...(t.id===id?{title:values.title.trim()}:{})};changed('投稿を編集しました');d.close();render(false);},'変更を保存');}return;}
if(b.dataset.report){modal('通報デモ',`<p>理由を選び、確認してください。実際の送信や投稿の削除は行いません。</p><label for="report-reason">通報理由</label><select id="report-reason"><option>迷惑行為・広告</option><option>誹謗中傷</option><option>個人情報</option><option>その他</option></select>`,d=>{const reason=$('#report-reason').value;d.close();modal('通報内容の確認',`<p>理由：${esc(reason)}</p><p>これはデモです。外部に送信されません。</p>`,dialog=>{dialog.close();notice('通報デモが完了しました。実送信は行っていません。');},'デモを完了する');},'確認へ');return;}
if(b.id==='reset-data'){modal('デモデータを初期化しますか？','<p>このデモの投稿・返信・編集・削除・保存一覧を初期化します。他の保存キーは残ります。</p>',d=>{try{localStorage.removeItem(KEY);state=blank();temporary=false;$('#storage-warning').hidden=true;d.close();render();notice('デモデータを初期化しました。固定データに戻りました。');}catch{d.close();storageWarning('初期化できません。ブラウザの保存設定を確認してください。');notice('初期化に失敗しました。既存のデータは維持しています。');}},'初期化する');}
});
$('.skip').addEventListener('click',e=>{e.preventDefault();$('#main').focus();$('#main').scrollIntoView();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#primary-nav').classList.contains('open')){closeMenu();$('#menu-toggle').focus();}});
window.addEventListener('hashchange',()=>{if(data)render();});
fetch(BASE+'fixtures/content.json').then(r=>{if(!r.ok)throw Error('HTTP '+r.status);return r.json();}).then(d=>{data=d;readState();render(false);}).catch(()=>{$('#main').innerHTML='<h1>攻略データを読み込めません</h1><p>ローカル配信と共通データの配置を確認し、再読込してください。</p><button onclick="location.reload()">再読込</button>';});
})();
