from pathlib import Path
import json, hashlib, datetime, subprocess
root=Path(__file__).resolve().parent
common=root.parent/'experiments/social-game'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
run=json.loads((common/'RUN-TEMPLATE.json').read_text(encoding='utf-8-sig'))
run.update(run_id='astra-solo-01',status='implementing_and_self_testing',baseline_commit='16ba7663e9a584856d3c0b4b7ce707bf86715b87',baseline_manifest_sha256=sha(common/'baseline.json'),prompt_sha256=sha(root/'prompt.txt'),output_directory=str(root),mode='solo',requested_settings={'model':'Astra','reasoning':None,'service_tier':None},observed_settings={'model':'GPT-6 / Codex (developer context); exact serving model identifier unavailable','reasoning':None,'service_tier':None},browser_preflight={'status':'PASS','actor':'implementation actor (this task)','evidence':'evidence/environment.png','details':'Both SVGs loaded; input filled; Tab focused confirmation button; Enter produced expected confirmation. Current-task connection succeeded before implementation.'},review_policy={'self_review':True,'independent_review':'not performed; no delegation allowed; independent evaluator may review frozen initial snapshot later','midpoint_advice':0},stages=[{'name':'preparation','start_utc':'2026-09-07T14:57:14.350Z','end_utc':'2026-09-07T14:59:18.615Z','duration_seconds':124.265,'waiting_seconds':None,'notes':'First timestamp is browser navigation evidence; earlier reading time unavailable. Includes user permission wait, duration not separately exposed.'},{'name':'implementation','start_utc':'2026-09-07T14:59:18.615Z','end_utc':'2026-09-07T15:07:02.297Z','duration_seconds':463.682,'waiting_seconds':None,'notes':'Empty output confirmed after authorized prior-log relocation. Includes design decisions and code writing.'},{'name':'self_verification_and_fixes','start_utc':'2026-09-07T15:07:02.297Z','end_utc':None,'duration_seconds':None,'waiting_seconds':None}],parent_usage=None,worker_usage=None,cost=None,incidents=[{'type':'nonempty_output','resolution':'User explicitly permitted moving four prior files to sibling game-astra-solo-01-prior-logs-20260907-235918. Contents were not read.'},{'type':'preflight_console','detail':'Environment page reported one console error; it did not block data, images, keyboard, or screenshot. Site uses inline empty favicon.'},{'type':'tool_probe','detail':'Playwright function attempted process.cwd for tool version/path; sandbox reported process is not defined; no app pageerror.'}])
run['budget']={'time_limit':None,'token_limit':None,'reason':'No explicit limit requested; completion bounded by shared acceptance.'}
run['tools']={'python':subprocess.check_output(['python','--version'],text=True).strip(),'node':subprocess.check_output(['node','--version'],text=True).strip(),'browser':'Playwright MCP, version pending browser observation','cli_calls':'No model CLI invocation or child agent calls.'}
run['usage_notes']={'input':None,'cached_input':None,'output':None,'reasoning_output':None,'noncached_input':None,'total':None,'reason':'Per-turn raw usage, reasoning settings, serving tier and billing are not exposed to this task. No model CLI was invoked; no estimated token or cost totals fabricated. Parent and solo implementation actor are the same actor, not summed twice.'}
run['followup_authorization']={'user_text':'許可します','scope':'Relocate existing four logs and create empty requested output directory.'}
run['prompt_record_note']='UTF-8 transcription of task prompt, LF-normalized; SHA256 identifies this saved transcription. Context/system instructions are not included in the task-prompt hash.'
(root/'run.json').write_text(json.dumps(run,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
(root/'evidence'/'environment-log.txt').write_text('Fixed input check: PASS\nBrowser actor: self\nImage c01.svg: loaded\nImage e01.svg: loaded\nInput: Astra単騎 接続確認\nTab focus: 確認する\nEnter result: 確認済み：Astra単騎 接続確認\nScreenshot: environment.png\n',encoding='utf-8')
