'use strict';
(() => {
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v)), mix=(a,b,t)=>a+(b-a)*t;
const reduced=matchMedia('(prefers-reduced-motion: reduce)'), KEY='paper-moon:v1';
const MOODS={day:{i:0,time:'10:24 AM',caption:'窓辺の光と、淹れたての香り。',intro:'何もしない時間も、いい時間。',name:'ひる',paper:'#f4f0e7',ink:'#2e493e'},dusk:{i:1,time:'05:46 PM',caption:'今日が、やさしくほどけていく。',intro:'がんばった今日に、ひと息を。',name:'ゆうぐれ',paper:'#f2e4d9',ink:'#654539'},night:{i:2,time:'09:18 PM',caption:'街が眠ったら、自分の時間。',intro:'静かな夜に、好きなことを。',name:'よる',paper:'#242b3b',ink:'#eadfbe'}};
const CUPS={sage:{color:'#8ca994',name:'SAGE GREEN'},cream:{color:'#e7d7b5',name:'CREAM'},rose:{color:'#c78f7f',name:'DUSTY ROSE'}}, BLENDS={house:'木漏れ日',citrus:'ひだまり',deep:'夜ふかし'};
let stored=null,persistent=true;
let raw=null;try{raw=localStorage.getItem(KEY);}catch{persistent=false;}try{stored=JSON.parse(raw||'null');}catch{stored=null;}
const own=(o,k)=>typeof k==='string'&&Object.hasOwn(o,k);
const valid=r=>r&&own(MOODS,r.mood)&&own(CUPS,r.cup)&&own(BLENDS,r.blend)&&Number.isFinite(r.at)&&r.at>0&&r.at<8640000000000000;
const state={mood:own(MOODS,stored?.mood)?stored.mood:'day',cup:own(CUPS,stored?.cup)?stored.cup:'sage',blend:own(BLENDS,stored?.blend)?stored.blend:'house',lamp:typeof stored?.lamp==='boolean'?stored.lamp:true,growth:Number.isInteger(stored?.growth)?clamp(stored.growth,0,2):0,moments:Array.isArray(stored?.moments)?stored.moments.filter(valid).slice(0,12):[]};
let toastTimer;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{if(persistent)toast('保存できないため、このタブの中だけで記録します。');persistent=false;}$('.collection-dot').hidden=!state.moments.length;}
// Small, deterministic mesh builder: all visible objects are real geometry.
const rgb=h=>[1,3,5].map(i=>parseInt(h.slice(i,i+2),16)/255),sub=(a,b)=>a.map((v,i)=>v-b[i]);
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm=a=>{const l=Math.hypot(...a)||1;return a.map(v=>v/l);},dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function matmul(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;}
function lookAt(eye,target){const z=norm(sub(eye,target)),x=norm(cross([0,1,0],z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-dot(x,eye),-dot(y,eye),-dot(z,eye),1]);}
function ortho(l,r,b,t,n,f){return new Float32Array([2/(r-l),0,0,0,0,2/(t-b),0,0,0,0,-2/(f-n),0,-(r+l)/(r-l),-(t+b)/(t-b),-(f+n)/(f-n),1]);}
class Geometry{
 constructor(){this.data=[];}
 tri(a,b,c,color,flag=0,uv=[[0,0],[0,0],[0,0]]){const n=norm(cross(sub(b,a),sub(c,a))),co=Array.isArray(color)?color:rgb(color);[a,b,c].forEach((p,i)=>this.data.push(...p,...n,...co,...uv[i],flag));}
 quad(a,b,c,d,color,flag=0,rect=[0,0,1,1]){const[u,v,w,h]=rect;this.tri(a,b,c,color,flag,[[u,v+h],[u+w,v+h],[u+w,v]]);this.tri(a,c,d,color,flag,[[u,v+h],[u+w,v],[u,v]]);}
 box(x,y,z,w,h,d,color,yaw=0){const cs=Math.cos(yaw),sn=Math.sin(yaw),p=[[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]].map(([a,b,c])=>[x+a*w/2*cs+c*d/2*sn,y+b*h/2,z-a*w/2*sn+c*d/2*cs]);[[4,5,6,7],[1,0,3,2],[0,4,7,3],[5,1,2,6],[7,6,2,3],[0,1,5,4]].forEach(f=>this.quad(...f.map(i=>p[i]),color));}
 cylinder(x,y,z,rb,rt,h,color,seg=20,flag=0){for(let i=0;i<seg;i++){const a=i/seg*6.283185,b=(i+1)/seg*6.283185,p=(t,r,dy)=>[x+Math.cos(t)*r,y+dy,z+Math.sin(t)*r];this.quad(p(b,rb,-h/2),p(a,rb,-h/2),p(a,rt,h/2),p(b,rt,h/2),color,flag);this.tri([x,y+h/2,z],p(b,rt,h/2),p(a,rt,h/2),color,flag);this.tri([x,y-h/2,z],p(a,rb,-h/2),p(b,rb,-h/2),color,flag);}}
 beam(a,b,r,color,seg=8){const axis=norm(sub(b,a)),u=norm(cross(axis,Math.abs(axis[1])>.9?[1,0,0]:[0,1,0])),v=cross(axis,u),p=(c,t)=>c.map((n,i)=>n+r*(Math.cos(t)*u[i]+Math.sin(t)*v[i]));for(let i=0;i<seg;i++){const s=i/seg*6.283185,t=(i+1)/seg*6.283185;this.quad(p(a,s),p(a,t),p(b,t),p(b,s),color);this.tri(b,p(b,s),p(b,t),color);}}
 sphere(x,y,z,rx,ry,rz,color,segs=16,rings=8){const p=(a,b)=>[x+rx*Math.sin(b)*Math.cos(a),y+ry*Math.cos(b),z+rz*Math.sin(b)*Math.sin(a)];for(let j=0;j<rings;j++)for(let i=0;i<segs;i++)this.quad(p(i/segs*6.283185,j/rings*Math.PI),p((i+1)/segs*6.283185,j/rings*Math.PI),p((i+1)/segs*6.283185,(j+1)/rings*Math.PI),p(i/segs*6.283185,(j+1)/rings*Math.PI),color);}
 torus(x,y,z,r,t,color){const p=(a,b)=>[x+(r+t*Math.cos(b))*Math.cos(a),y+(r+t*Math.cos(b))*Math.sin(a),z+t*Math.sin(b)];for(let i=0;i<16;i++)for(let j=0;j<6;j++)this.quad(p(i/16*6.283185,j/6*6.283185),p((i+1)/16*6.283185,j/6*6.283185),p((i+1)/16*6.283185,(j+1)/6*6.283185),p(i/16*6.283185,(j+1)/6*6.283185),color);}
 arch(x,y,z,w,h,color,flag=0){const r=w/2,shoulder=y+h-r;this.quad([x-r,y,z],[x+r,y,z],[x+r,shoulder,z],[x-r,shoulder,z],color,flag);for(let i=0;i<24;i++){const a=i/24*Math.PI,b=(i+1)/24*Math.PI;this.tri([x,shoulder,z],[x+Math.cos(a)*r,shoulder+Math.sin(a)*r,z],[x+Math.cos(b)*r,shoulder+Math.sin(b)*r,z],color,flag);}}
 leaf(base,tip,width,color){const axis=sub(tip,base),side=norm(cross(axis,[0,0,1])),mid=base.map((v,i)=>v+axis[i]*.5),ridge=mid.map((v,i)=>v+(i===2?.08:0)),left=mid.map((v,i)=>v+side[i]*width),right=mid.map((v,i)=>v-side[i]*width);this.tri(base,left,ridge,color);this.tri(left,tip,ridge,color);this.tri(base,ridge,right,color);this.tri(ridge,tip,right,color);}
}
function buildCafe(s){
 const g=new Geometry(),wood='#ae8260',sage='#779584';
 g.box(0,-.02,0,6.3,.22,4.6,'#ceba97');g.box(0,.10,0,6.37,.09,4.67,'#f1e5c9');g.box(0,-.15,0,6.23,.035,4.53,'#e7d8b9');
 for(let x=0;x<9;x++)for(let z=0;z<6;z++)g.box(-2.78+x*.69,.162,-1.91+z*.69,.681,.035,.681,(x+z)%2?'#e4dac0':'#f1e8d1');
 g.box(0,1.85,-2.19,6.3,3.45,.13,'#f1dfbd');g.box(-3.08,1.85,0,.13,3.45,4.5,'#d9dfc3');g.box(-2.993,.69,0,.035,1.04,4.35,'#a5b59a');g.box(-2.95,1.24,0,.12,.09,4.39,'#b9c6a6');
 for(let i=0;i<13;i++)g.box(-2.967,.7,-2.07+i*.345,.025,.99,.012,'#8fa588');
 g.box(0,.31,-2.099,6.12,.27,.08,'#dfc39c');g.box(-2.956,.28,0,.09,.22,4.4,'#a0ad8e');g.box(0,3.59,-2.19,6.36,.07,.20,'#f8ead0');g.box(-3.08,3.59,0,.20,.07,4.56,'#e8e9ce');
 // Nested silhouettes read as layered cut paper.
 g.arch(-1.55,.84,-2.092,1.86,2.38,'#c5a47c');g.arch(-1.55,.94,-2.073,1.64,2.17,'#8aa59a');g.arch(-1.55,1.02,-2.053,1.46,2.00,'#bfd4be',2);
 g.sphere(-1.73,2.47,-2.031,.25,.25,.015,'#f1d69d',24,12);g.box(-1.55,1.98,-1.997,.065,1.97,.045,'#f5e8cb');g.box(-1.55,1.90,-1.995,1.48,.065,.045,'#f5e8cb');g.box(-1.55,.92,-1.94,1.96,.12,.37,'#ebd6ac');
 g.box(-2.949,2.60,.26,.05,1.0,.79,'#ab9979');g.box(-2.915,2.60,.26,.025,.91,.70,'#f3e8cf');g.sphere(-2.887,2.65,.26,.013,.26,.26,'#cf9e79',20,10);g.box(-2.80,1.58,.20,.46,.09,1.30,wood);
 ['#bba078','#718b75','#d7b68d','#a57562'].forEach((c,i)=>g.box(-2.72,1.84,-.24+i*.19,.27,.43+i%2*.08,.15,c));
 g.box(1.09,.80,-1.14,3.23,1.21,1.12,'#bf8b70');for(let i=0;i<21;i++)g.box(-.46+i*.153,.82,-.564,.11,1.11,.046,i%3?'#dfa88a':'#e6b597');g.box(1.09,1.444,-1.14,3.43,.125,1.23,'#eeddba');g.box(1.09,1.383,-1.14,3.38,.045,1.20,'#c1a17b');
 g.box(.26,1.77,-1.36,1.05,.54,.57,sage);g.box(.26,1.72,-1.059,.94,.35,.032,'#cad0b3');g.box(.26,2.058,-1.36,1.13,.07,.64,'#a2ae91');g.box(.26,1.517,-1.09,1.17,.035,.67,'#758275');g.box(.26,1.635,-1.02,.58,.12,.09,'#5c7568');g.beam([.25,1.75,-1.02],[.25,1.58,-.99],.025,'#b8b3a0');g.beam([.53,1.73,-1.01],[.69,1.73,-.93],.022,wood);[-.10,.10,.57].forEach(x=>g.sphere(x,1.87,-1.026,.04,.04,.02,'#f1dfb5',12,6));
 const cup=(x,y,z,c,r=.15)=>{g.cylinder(x,y+.035,z,r*1.5,r*1.5,.028,'#e7ddc3');g.cylinder(x,y+.16,z,r*.8,r,.22,c);g.cylinder(x,y+.272,z,r*.78,r*.78,.006,'#62452e');g.torus(x+r*.97,y+.17,z,r*.54,.024,c);};
 cup(.17,1.51,-.82,'#e9dcc1',.095);[.00,.39].forEach(x=>cup(x,2.05,-1.35,'#eee3c8',.105));g.cylinder(1.26,1.73,-1.38,.20,.20,.44,'#cfb98b',16);g.cylinder(1.26,1.973,-1.38,.225,.225,.056,wood,16);g.box(1.26,1.74,-1.172,.21,.20,.015,'#f3e7c8');
 g.box(2.09,1.54,-1.22,1.01,.06,.76,wood);for(let x of[1.64,2.54])for(let z of[-1.53,-.88])g.box(x,1.81,z,.035,.54,.035,'#b59d76');g.box(2.09,2.085,-1.22,1.01,.044,.76,'#dccba4');g.box(2.09,1.84,-1.55,.94,.48,.025,'#ead8b5');[1.82,2.27].forEach(x=>{g.sphere(x,1.67,-1.16,.18,.10,.22,'#c6995e',14,6);for(let j=0;j<3;j++)g.box(x-.085+j*.08,1.756,-1.16,.024,.009,.20,'#e2b879',.3);});
 g.box(.91,2.67,-2.058,1.31,1.04,.07,'#ac8d65');g.quad([.305,2.19,-2.010],[1.515,2.19,-2.010],[1.515,3.15,-2.010],[.305,3.15,-2.010],'#ffffff',1,[.5,0,.5,.5]);g.box(2.08,2.51,-1.96,.86,.07,.36,wood);[1.85,2.11,2.35].forEach((x,i)=>g.cylinder(x,2.71,-1.94,.088,.10,.33,['#99a87a','#d3aa77','#c9937a'][i],10));
 g.sphere(2.26,3.12,-2.045,.265,.265,.042,'#bdac83',24,12);g.sphere(2.26,3.12,-1.997,.225,.225,.011,'#f6edcf',24,12);g.beam([2.26,3.12,-1.98],[2.26,3.27,-1.98],.013,'#5f6f58',6);g.beam([2.26,3.12,-1.974],[2.38,3.07,-1.974],.012,'#5f6f58',6);
 g.quad([.23,.87,-.531],[1.95,.87,-.531],[1.95,1.20,-.531],[.23,1.20,-.531],'#ffffff',1,[0,0,.5,.25]);
 g.cylinder(-1.02,.60,.54,.075,.075,.86,wood,12);for(let a of[0,2.094,4.188])g.beam([-1.02,.37,.54],[-1.02+Math.cos(a)*.48,.21,.54+Math.sin(a)*.48],.045,wood);g.cylinder(-1.02,1.052,.54,.86,.86,.095,'#617b60',48);g.cylinder(-1.02,1.105,.54,.85,.85,.032,'#a5b799',48);
 function chair(x,z,yaw){const p=(a,y,b)=>[x+a*Math.cos(yaw)+b*Math.sin(yaw),y,z-a*Math.sin(yaw)+b*Math.cos(yaw)];for(let a of[-.23,.23])for(let b of[-.22,.22])g.beam(p(a*1.18,.20,b*1.18),p(a,.64,b),.032,wood);g.cylinder(x,.65,z,.37,.37,.07,'#c6aa7c',24);for(let a of[-.29,.29])g.beam(p(a,.68,-.24),p(a,1.24,-.29),.031,wood);const c=p(0,1.13,-.29);g.box(...c,.69,.30,.067,'#7e9a7e',yaw);}
 chair(-2.13,.08,.64);chair(-.77,1.76,3.07);cup(-1.10,1.126,.39,CUPS[s.cup].color,.155);g.sphere(-1.115,1.405,.38,.045,.003,.042,'#e7cc98',12,4);g.sphere(-1.055,1.405,.38,.045,.003,.042,'#e7cc98',12,4);g.tri([-1.151,1.408,.39],[-1.087,1.408,.465],[-1.02,1.408,.39],'#e7cc98');g.box(-.64,1.15,.83,.39,.045,.52,'#d59780',-.18);g.box(-.64,1.183,.83,.35,.019,.47,'#f6e5c4',-.18);g.box(-.63,1.195,.80,.23,.004,.025,'#9a9275',-.18);
 const px=2.10,pz=1.31;g.cylinder(px,.45,pz,.25,.39,.52,'#c28c6d');g.cylinder(px,.73,pz,.404,.404,.085,'#d59e7a');g.cylinder(px,.778,pz,.345,.345,.013,'#6c6043');for(let i=0;i<7+s.growth*2;i++){const a=i*2.399,h=.75+(i%3)*.20+s.growth*.06,r=.34+(i%2)*.19,root=[px,.79,pz],mid=[px+Math.cos(a)*r*.52,.79+h*.67,pz+Math.sin(a)*r*.52],tip=[px+Math.cos(a)*r,.79+h,pz+Math.sin(a)*r];g.beam(root,mid,.013,'#657b4c',6);g.leaf(mid,tip,.16+(i%2)*.055,['#79955d','#99ab70','#6b8759'][i%3]);}
 g.cylinder(-2.05,1.08,-1.91,.11,.15,.23,'#c19070',12);for(let i=0;i<5;i++){let a=i*1.256;g.leaf([-2.05,1.19,-1.91],[-2.05+Math.cos(a)*.18,1.49,-1.91+Math.sin(a)*.14],.066,'#8ba272');}
 g.box(.88,.64,1.60,.61,.86,.055,wood,-.08);g.box(.88,.64,1.30,.57,.86,.05,'#b09468',-.08);g.quad([.615,.29,1.655],[1.145,.29,1.613],[1.145,1.00,1.613],[.615,1.00,1.655],'#ffffff',1,[0,.5,.375,.5]);
 g.beam([.28,3.44,-2.10],[.28,3.44,-.23],.020,'#726952');g.beam([.28,3.44,-.23],[.28,2.83,-.23],.014,'#726952');g.cylinder(.28,2.77,-.23,.47,.16,.32,'#d5af76',32);g.cylinder(.28,2.604,-.23,.44,.44,.009,s.lamp?'#ffdc90':'#c1ad86',32,s.lamp?3:0);
 return new Float32Array(g.data);
}
const VERTEX=`attribute vec3 aPosition,aNormal,aColor;attribute vec2 aUV;attribute float aFlag;uniform mat4 uVP,uLightVP;varying vec3 vNormal,vColor,vWorld;varying vec2 vUV;varying float vFlag;varying vec4 vShadow;void main(){vNormal=aNormal;vColor=aColor;vWorld=aPosition;vUV=aUV;vFlag=aFlag;vShadow=uLightVP*vec4(aPosition,1.);gl_Position=uVP*vec4(aPosition,1.);}`;
const FRAGMENT=`precision highp float;varying vec3 vNormal,vColor,vWorld;varying vec2 vUV;varying float vFlag;varying vec4 vShadow;uniform sampler2D uAtlas,uShadow;uniform vec3 uAmbient,uKey;uniform float uNight,uLamp,uTexel;float depth(vec4 p){return dot(p,vec4(1.,1./255.,1./65025.,1./16581375.));}void main(){vec3 n=normalize(vNormal);if(!gl_FrontFacing)n=-n;vec3 base=vColor;if(vFlag>.5&&vFlag<1.5)base*=texture2D(uAtlas,vUV).rgb;vec3 sc=vShadow.xyz/vShadow.w*.5+.5;float sh=1.;if(sc.x>0.&&sc.x<1.&&sc.y>0.&&sc.y<1.&&sc.z<1.){sh=0.;for(int x=-1;x<=1;x++){for(int y=-1;y<=1;y++){sh+=sc.z-.0027<=depth(texture2D(uShadow,sc.xy+vec2(float(x),float(y))*uTexel))?1.:0.;}}sh/=9.;}vec3 ld=normalize(vec3(-3.,8.,5.));float diffuse=max(dot(n,ld),0.);float d=distance(vWorld,vec3(.28,2.58,-.23));float lamp=uLamp*(.12+uNight*.55)/(1.+d*d*.65);vec3 light=uAmbient*(.86+.14*max(n.y,0.))+uKey*diffuse*(.3+.7*sh)+vec3(1.,.68,.31)*lamp;vec3 color=base*light;if(vFlag>1.5&&vFlag<2.5)color=mix(vec3(.69,.79,.68),vec3(.92,.68,.32),uNight);if(vFlag>2.5)color=vec3(1.,.83,.51);float grain=fract(sin(dot(floor(vWorld*95.),vec3(12.9898,78.233,45.164)))*43758.5453);color*=.986+grain*.027;gl_FragColor=vec4(color,1.);}`;
const SHADOW_VERTEX=`attribute vec3 aPosition;uniform mat4 uVP;void main(){gl_Position=uVP*vec4(aPosition,1.);}`;
const SHADOW_FRAGMENT=`precision highp float;void main(){vec4 p=fract(gl_FragCoord.z*vec4(1.,255.,65025.,16581375.));p-=p.yzww*vec4(1./255.,1./255.,1./255.,0.);gl_FragColor=p;}`;
class CafeRenderer{
 constructor(canvas){
  this.canvas=canvas;this.gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false,preserveDrawingBuffer:false,powerPreference:'low-power'});if(!this.gl)throw Error('WebGL unavailable');
  this.yaw=.68;this.target=.68;this.velocity=0;this.dragging=false;this.mood=MOODS[state.mood].i;this.moodTarget=this.mood;this.raf=0;this.frames=0;this.lost=false;this.init();
  this.resizeObserver=new ResizeObserver(()=>{this.resize();this.wake();});this.resizeObserver.observe(canvas);
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;cancelAnimationFrame(this.raf);this.raf=0;setStatic(true);toast('省電力の展示表示に切り替えました。');});
  canvas.addEventListener('webglcontextrestored',()=>{try{this.lost=false;this.init();setStatic(false);this.resize();this.wake();}catch{this.lost=true;setStatic(true);}});
 }
 program(v,f){const gl=this.gl,p=gl.createProgram();for(const[type,source]of[[gl.VERTEX_SHADER,v],[gl.FRAGMENT_SHADER,f]]){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const message=gl.getShaderInfoLog(s);gl.deleteShader(s);throw Error(message);}gl.attachShader(p,s);gl.deleteShader(s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
 init(){const gl=this.gl;this.main=this.program(VERTEX,FRAGMENT);this.shadow=this.program(SHADOW_VERTEX,SHADOW_FRAGMENT);this.buffer=gl.createBuffer();this.lightVP=matmul(ortho(-5.2,5.2,-4.8,4.8,.1,24),lookAt([-5,10,7],[0,1,0]));this.makeAtlas();
  this.shadowSize=Math.min(1024,gl.getParameter(gl.MAX_TEXTURE_SIZE));this.shadowTexture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.shadowTexture);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,this.shadowSize,this.shadowSize,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
  this.depthBuffer=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,this.depthBuffer);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,this.shadowSize,this.shadowSize);this.fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,this.shadowTexture,0);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,this.depthBuffer);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('Shadow framebuffer unavailable');gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.enable(gl.DEPTH_TEST);gl.disable(gl.BLEND);this.rebuild();this.resize();
 }
 makeAtlas(){const gl=this.gl,c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d');x.fillStyle='#f0e4c8';x.fillRect(0,0,1024,512);x.fillStyle='#3c5544';x.textAlign='center';x.textBaseline='middle';x.font='38px Georgia';x.fillText('PAPER MOON',256,62);x.font='11px sans-serif';x.fillText('COFFEE  /  QUIET MOMENTS',256,100);x.fillStyle='#3d5746';x.fillRect(512,0,512,256);x.fillStyle='#e9dec1';x.font='35px Georgia';x.fillText('slow bar',768,50);x.lineWidth=1;x.strokeStyle='#c4c9a5';x.beginPath();x.moveTo(565,84);x.lineTo(971,84);x.stroke();x.font='20px Georgia';['house blend     480','café au lait     520','a little pause     ∞'].forEach((s,i)=>x.fillText(s,768,120+i*42));x.fillStyle='#3d5746';x.fillRect(0,256,384,256);x.fillStyle='#eee4c8';x.font='42px Georgia';x.fillText('SLOW',192,319);x.fillText('DAYS',192,366);x.font='16px Georgia';x.fillText('coffee & little things',192,420);x.font='24px Georgia';x.fillText('YOU ARE WELCOME',192,469);
  this.atlas=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,this.atlas);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,c);gl.generateMipmap(gl.TEXTURE_2D);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR_MIPMAP_LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);
 }
 bind(program){const gl=this.gl;gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);const attrs=[['aPosition',3,0],['aNormal',3,12],['aColor',3,24],['aUV',2,36],['aFlag',1,44]];for(const[n,size,offset]of attrs){const a=gl.getAttribLocation(program,n);if(a>=0){gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,size,gl.FLOAT,false,48,offset);}}}
 uniform(program,name,type,...v){const gl=this.gl;gl[type](gl.getUniformLocation(program,name),...v);}
 rebuild(){if(this.lost)return;const gl=this.gl,data=buildCafe(state);this.count=data.length/12;gl.bindBuffer(gl.ARRAY_BUFFER,this.buffer);gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);this.shadowDirty=true;this.wake();}
 resize(){const b=this.canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);this.w=Math.max(1,b.width);this.h=Math.max(1,b.height);const w=Math.round(this.w*dpr),h=Math.round(this.h*dpr);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h;}}
 camera(){const aspect=this.w/this.h,view=lookAt([Math.sin(this.yaw)*10,7.6,Math.cos(this.yaw)*10],[0,1.45,0]);let xmin=Infinity,xmax=-Infinity,ymin=Infinity,ymax=-Infinity;for(const x of[-3.2,3.2])for(const y of[-.18,3.64])for(const z of[-2.36,2.36]){const px=view[0]*x+view[4]*y+view[8]*z+view[12],py=view[1]*x+view[5]*y+view[9]*z+view[13];xmin=Math.min(xmin,px);xmax=Math.max(xmax,px);ymin=Math.min(ymin,py);ymax=Math.max(ymax,py);}const height=Math.max(ymax-ymin,(xmax-xmin)/aspect)*1.09,cx=(xmin+xmax)/2,cy=(ymin+ymax)/2;this.vp=matmul(ortho(cx-height*aspect/2,cx+height*aspect/2,cy-height/2,cy+height/2,.1,30),view);}
 draw(){if(this.lost||!this.count)return;const gl=this.gl;this.camera();
  if(this.shadowDirty){gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);gl.viewport(0,0,this.shadowSize,this.shadowSize);gl.clearColor(1,1,1,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.bind(this.shadow);this.uniform(this.shadow,'uVP','uniformMatrix4fv',false,this.lightVP);gl.drawArrays(gl.TRIANGLES,0,this.count);gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.shadowDirty=false;}
  gl.viewport(0,0,this.canvas.width,this.canvas.height);gl.clearColor(0,0,0,0);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);this.bind(this.main);this.uniform(this.main,'uVP','uniformMatrix4fv',false,this.vp);this.uniform(this.main,'uLightVP','uniformMatrix4fv',false,this.lightVP);
  const amb=[[.78,.79,.73],[.84,.67,.54],[.32,.37,.49]],key=[[.32,.30,.25],[.38,.25,.16],[.19,.22,.36]],i=Math.min(1,Math.floor(this.mood)),t=this.mood-i;
  this.uniform(this.main,'uAmbient','uniform3fv',amb[i].map((v,j)=>mix(v,amb[i+1][j],t)));this.uniform(this.main,'uKey','uniform3fv',key[i].map((v,j)=>mix(v,key[i+1][j],t)));this.uniform(this.main,'uNight','uniform1f',clamp(this.mood-1,0,1));this.uniform(this.main,'uLamp','uniform1f',state.lamp?1:0);this.uniform(this.main,'uTexel','uniform1f',1/this.shadowSize);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.atlas);this.uniform(this.main,'uAtlas','uniform1i',0);gl.activeTexture(gl.TEXTURE1);gl.bindTexture(gl.TEXTURE_2D,this.shadowTexture);this.uniform(this.main,'uShadow','uniform1i',1);gl.drawArrays(gl.TRIANGLES,0,this.count);this.frames++;this.hotspot($('#lamp'),[.65,3.2,-.15]);this.hotspot($('#plant'),[2.78,1.55,1.47]);
 }
 hotspot(el,p){const m=this.vp,x=m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],y=m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13];el.style.left=clamp((x*.5+.5)*this.w,25,this.w-25)+'px';el.style.top=clamp((.5-y*.5)*this.h,25,this.h-50)+'px';}
 wake(){if(this.raf||this.lost||document.hidden)return;this.last=performance.now();this.raf=requestAnimationFrame(t=>this.tick(t));}
 tick(now){this.raf=0;const dt=clamp((now-this.last)/1000,.001,.035);this.last=now;if(!this.dragging){if(reduced.matches){this.yaw=this.target;this.velocity=0;}else{this.velocity+=((this.target-this.yaw)*110-this.velocity*18)*dt;this.yaw+=this.velocity*dt;}}this.mood=reduced.matches?this.moodTarget:mix(this.mood,this.moodTarget,1-Math.exp(-dt*8));const moving=Math.abs(this.target-this.yaw)>.0002||Math.abs(this.velocity)>.001||Math.abs(this.moodTarget-this.mood)>.001;if(!moving){this.yaw=this.target;this.mood=this.moodTarget;}this.draw();if(moving&&!this.dragging&&!document.hidden)this.raf=requestAnimationFrame(t=>this.tick(t));}
 turn(amount){this.target=clamp(this.target+amount,.26,1.13);this.wake();}
 pause(){cancelAnimationFrame(this.raf);this.raf=0;}
}
let renderer=null;
function setStatic(on){$('#scene').classList.toggle('static',on);$('#scene').classList.toggle('ready',!on);$('#left').disabled=on;$('#right').disabled=on;$('#hint').textContent=on?'展示モード · 一杯を淹れて、ひと息を':'左右にスワイプして、のぞいてみて';if(on){$('#lamp').style.cssText='';$('#plant').style.cssText='';}}
try{renderer=new CafeRenderer($('#cafe'));setStatic(false);}catch(e){console.warn('PAPER MOON: static fallback.',e.message);setStatic(true);}
// Sound is opt-in and synthesized locally; there are no audio downloads.
let audio=null,soundOn=false;
async function sound(note=0){if(!soundOn)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')await audio.resume();const o=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type='sine';o.frequency.setValueAtTime([523.25,659.25,783.99,1046.5][note%4],now);g.gain.setValueAtTime(0,now);g.gain.linearRampToValueAtTime(.055,now+.012);g.gain.exponentialRampToValueAtTime(.001,now+.42);o.connect(g);g.connect(audio.destination);o.start(now);o.stop(now+.45);o.onended=()=>{o.disconnect();g.disconnect();};}catch{soundOn=false;updateSound();toast('この環境では操作音を利用できません。');}}
function updateSound(){$('#sound').setAttribute('aria-pressed',String(soundOn));$('#sound').setAttribute('aria-label',soundOn?'操作音をオフにする':'操作音をオンにする');}
$('#sound').addEventListener('click',()=>{soundOn=!soundOn;updateSound();sound(1);});
function updateFallback(){const svg=$('#fallback');svg.style.filter=state.mood==='night'?'brightness(.60) saturate(.72)':state.mood==='dusk'?'sepia(.18) saturate(1.1)':'none';$('#fallback-cup').setAttribute('fill',CUPS[state.cup].color);$('#fallback-lamp').setAttribute('fill',state.lamp?'#ffebae':'#a99b7d');$('#fallback-leaf-1').setAttribute('opacity',state.growth>=1?'1':'0');$('#fallback-leaf-2').setAttribute('opacity',state.growth>=2?'1':'0');}
function applyMood(name,announce=false){state.mood=name;document.documentElement.dataset.mood=name;const m=MOODS[name];$('#caption').textContent=m.caption;$('#intro-copy').textContent=m.intro;$('#time-value').textContent=m.time;$('meta[name=theme-color]').content=m.paper;$$('.time-picker button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mood===name)));if(renderer){renderer.moodTarget=m.i;renderer.wake();}updateFallback();if(announce){save();sound(m.i);}}
$$('.time-picker button').forEach(b=>b.addEventListener('click',()=>applyMood(b.dataset.mood,true)));
$('#lamp').addEventListener('click',()=>{state.lamp=!state.lamp;$('#lamp').setAttribute('aria-pressed',String(state.lamp));renderer?.rebuild();updateFallback();save();sound(1);toast(state.lamp?'小さな灯りを、ともしました。':'灯りを消して、窓の光だけに。');});
$('#plant').addEventListener('click',()=>{if(state.growth<2){state.growth++;renderer?.rebuild();updateFallback();save();toast(state.growth===1?'新しい葉が、ひらきました。':'緑が、もう少しにぎやかに。');}else toast('今日の緑は、ごきげんです。');sound(2);});
$('#left').addEventListener('click',()=>renderer?.turn(-.18));$('#right').addEventListener('click',()=>renderer?.turn(.18));
let drag=null;
$('#scene').addEventListener('pointerdown',e=>{if(e.target.closest('button')||!renderer||renderer.lost||!e.isPrimary||e.button!==0)return;renderer.pause();renderer.dragging=true;renderer.target=renderer.yaw;renderer.velocity=0;drag={id:e.pointerId,x:e.clientX,yaw:renderer.yaw,prev:e.clientX,time:performance.now(),velocity:0};$('#scene').setPointerCapture(e.pointerId);});
$('#scene').addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const now=performance.now(),raw=drag.yaw+(e.clientX-drag.x)*.0037,lo=.26,hi=1.13;renderer.yaw=raw<lo?lo+(raw-lo)*.2:raw>hi?hi+(raw-hi)*.2:raw;renderer.target=renderer.yaw;drag.velocity=(e.clientX-drag.prev)*.0037/Math.max(.008,(now-drag.time)/1000);drag.prev=e.clientX;drag.time=now;renderer.wake();});
function endDrag(e){if(!drag||(e?.pointerId!==undefined&&e.pointerId!==drag.id))return;const v=performance.now()-drag.time>90?0:clamp(drag.velocity,-2,2);renderer.dragging=false;renderer.velocity=v;renderer.target=clamp(renderer.yaw+v*.12,.26,1.13);drag=null;renderer.wake();}
['pointerup','pointercancel','lostpointercapture'].forEach(type=>$('#scene').addEventListener(type,endDrag));
$('#scene').addEventListener('keydown',e=>{if(e.target!==$('#scene'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();renderer?.turn(e.key==='ArrowLeft'?-.18:.18);}});
const sheet=$('#sheet');let activePanel='',pouring=false,automatic=false,brewValue=0,brewDone=false,brewFrame=0,brewLast=0;
function stopPour(){pouring=false;automatic=false;cancelAnimationFrame(brewFrame);brewFrame=0;$('#pour').classList.remove('pouring');if(!brewDone&&brewValue>0)$('#pour-label').textContent='もう一度長押しで、続きを注ぐ';}
function openPanel(name,title,eyebrow){stopPour();activePanel=name;$$('.sheet-inner>section').forEach(p=>p.hidden=p.id!==name+'-panel');$('#sheet-title').textContent=title;$('#sheet-eyebrow').textContent=eyebrow;if(!sheet.open){sheet.showModal();document.body.style.overflow='hidden';}sheet.scrollTop=0;$('#close').focus({preventScroll:true});}
function closeSheet(){sheet.close();}
$('#close').addEventListener('click',closeSheet);$('#back').addEventListener('click',closeSheet);
sheet.addEventListener('close',()=>{stopPour();activePanel='';document.body.style.overflow='';});
sheet.addEventListener('click',e=>{if(e.target!==sheet)return;const r=sheet.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeSheet();});
function updateChoices(){const c=CUPS[state.cup];$('#cup-art').style.setProperty('--cup',c.color);$('#cup-name').textContent=c.name;$$('[data-cup]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.cup===state.cup)));$$('[data-blend]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.blend===state.blend)));}
$$('[data-cup]').forEach(b=>b.addEventListener('click',()=>{if(brewDone)return;state.cup=b.dataset.cup;updateChoices();renderer?.rebuild();updateFallback();save();sound(1);}));
$$('[data-blend]').forEach(b=>b.addEventListener('click',()=>{if(brewDone)return;state.blend=b.dataset.blend;updateChoices();save();sound(0);}));
function showProgress(){const n=Math.round(brewValue*100);$('#cup-art').style.setProperty('--fill',brewValue.toFixed(4));$('#progress').value=n;$('#percent').replaceChildren(document.createTextNode(String(n)),Object.assign(document.createElement('small'),{textContent:'%'}));$('#pour').style.setProperty('--progress',n+'%');}
function openBrew(){brewValue=0;brewDone=false;$('#complete').hidden=true;$('#pour').hidden=false;$('#auto-pour').hidden=false;$('#pour-label').textContent='長押しで、ゆっくり注ぐ';$('#cup-art').classList.remove('done');$('#brew-description').textContent='好きな色を選んで、ゆっくり注いでみて。';$$('#brew-panel fieldset button').forEach(b=>b.disabled=false);updateChoices();showProgress();openPanel('brew','今日の気分を、一杯に。','THE SLOW BAR');sound(0);}
function finishBrew(){if(brewDone)return;brewDone=true;stopPour();brewValue=1;showProgress();state.moments.unshift({at:Date.now(),cup:state.cup,blend:state.blend,mood:state.mood});state.moments=state.moments.slice(0,12);save();$('#cup-art').classList.add('done');$('#pour').hidden=true;$('#auto-pour').hidden=true;$('#complete').hidden=false;$$('#brew-panel fieldset button').forEach(b=>b.disabled=true);$('#sheet-title').textContent='あなただけの、一杯。';$('#brew-description').textContent=BLENDS[state.blend]+'を淹れました。ひと息の記録に残しています。';$('#brew-card').focus({preventScroll:true});sound(3);}
function brewTick(now){if(!pouring||document.hidden)return;brewValue=Math.min(1,brewValue+Math.min(50,now-brewLast)/2600);brewLast=now;showProgress();if(brewValue>=1)finishBrew();else brewFrame=requestAnimationFrame(brewTick);}
function startPour(auto=false){if(brewDone||pouring||activePanel!=='brew')return;automatic=auto;pouring=true;brewLast=performance.now();$('#pour').classList.add('pouring');$('#pour-label').textContent='ゆっくり、ゆっくり。';brewFrame=requestAnimationFrame(brewTick);sound(0);}
$('#open-brew').addEventListener('click',openBrew);$('#auto-pour').addEventListener('click',()=>startPour(true));
$('#pour').setAttribute('aria-label','長押しで注ぐ。キーボードの決定キーでは自動抽出。');
$('#pour').addEventListener('pointerdown',e=>{if(!e.isPrimary||e.button!==0)return;e.preventDefault();$('#pour').setPointerCapture(e.pointerId);startPour(false);});
['pointerup','pointercancel','lostpointercapture'].forEach(type=>$('#pour').addEventListener(type,()=>{if(!automatic)stopPour();}));
$('#pour').addEventListener('click',e=>{if(e.detail===0)startPour(true);});$('#pour').addEventListener('contextmenu',e=>e.preventDefault());
$('#collection').addEventListener('click',()=>{openPanel('collection','ひと息の、コレクション。','YOUR LITTLE MOMENTS');const list=$('#collection-list');list.replaceChildren();if(!state.moments.length){const empty=document.createElement('div');empty.className='collection-empty';const p=document.createElement('p');p.textContent='Your first little pause.';const text=document.createElement('small');text.textContent='一杯を淹れると、ここに記録が残ります。';empty.append(p,text);list.append(empty);}else state.moments.forEach((r,i)=>{const row=document.createElement('div');row.className='collection-item';const stamp=document.createElement('span');stamp.className='stamp';stamp.textContent=['☼','◒','☽'][MOODS[r.mood].i];stamp.setAttribute('aria-hidden','true');const info=document.createElement('div'),name=document.createElement('strong'),meta=document.createElement('small'),number=document.createElement('span');name.textContent=BLENDS[r.blend];meta.textContent=new Intl.DateTimeFormat('ja-JP',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(r.at)+' · '+MOODS[r.mood].name+' · '+CUPS[r.cup].name;number.className='number';number.textContent=String(state.moments.length-i).padStart(2,'0');info.append(name,meta);row.append(stamp,info,number);list.append(row);});$('#storage-note').textContent=persistent?'このブラウザだけに、最新12杯を記録します。':'保存領域が使えないため、このタブの中だけで記録しています。';});
$('#about').addEventListener('click',()=>openPanel('about','小さな場所に、大きな余白。','ABOUT PAPER MOON'));
// Repaint and copy in the same task: no preserveDrawingBuffer overhead in normal use.
function worldSnapshot(){const c=document.createElement('canvas');c.width=1000;c.height=760;const ctx=c.getContext('2d');if(renderer&&!renderer.lost){const r=renderer,old={w:r.w,h:r.h,cw:r.canvas.width,ch:r.canvas.height,mood:r.mood};try{r.w=1000;r.h=760;r.canvas.width=1000;r.canvas.height=760;r.mood=r.moodTarget;r.draw();ctx.drawImage(r.canvas,0,0);}finally{r.w=old.w;r.h=old.h;r.canvas.width=old.cw;r.canvas.height=old.ch;r.mood=old.mood;r.draw();}return Promise.resolve(c);}return new Promise((resolve,reject)=>{const image=new Image(),svg=new XMLSerializer().serializeToString($('#fallback')),url=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));image.onload=()=>{ctx.drawImage(image,0,0,1000,760);URL.revokeObjectURL(url);resolve(c);};image.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Fallback image failed'));};image.src=url;});}
let cardBlob=null,cardURL='',cardSequence=0,cardTimer;
async function makeCard(){const seq=++cardSequence;$('#save-card').disabled=true;$('#share-card').disabled=true;try{const shot=await worldSnapshot();if(seq!==cardSequence)return;const c=document.createElement('canvas');c.width=1080;c.height=1440;const x=c.getContext('2d'),m=MOODS[state.mood];x.fillStyle='#faf6ed';x.fillRect(0,0,1080,1440);x.fillStyle=m.paper;x.fillRect(28,28,1024,1384);x.fillStyle=m.ink;x.textAlign='center';x.font='68px Georgia';x.fillText('PAPER MOON',540,149);x.font='18px sans-serif';x.fillText('A LITTLE PLACE TO EXHALE',540,195);x.font='30px serif';x.fillText('余白を、ひとくち。',540,276);x.globalAlpha=state.mood==='night'?.45:.55;x.fillStyle=state.mood==='night'?'#d1c4a1':state.mood==='dusk'?'#e3b08b':'#e1d3b4';x.beginPath();x.arc(705,582,state.mood==='night'?140:226,0,Math.PI*2);x.fill();x.globalAlpha=1;x.drawImage(shot,40,315,1000,760);x.fillStyle=m.ink;x.font='30px serif';const message=$('#message').value.trim()||'今日は、急がなくてもいい。';let lines=[''];for(const char of Array.from(message)){if(x.measureText(lines[lines.length-1]+char).width>850)lines.push('');lines[lines.length-1]+=char;}lines.slice(0,3).forEach((line,i)=>x.fillText(line,540,1151+i*45));x.globalAlpha=.65;x.font='17px sans-serif';x.fillText(MOODS[state.mood].name.toUpperCase()+'  /  '+BLENDS[state.blend]+'  /  '+CUPS[state.cup].name,540,1298);x.font='16px Georgia';x.fillText(new Intl.DateTimeFormat('ja-JP',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())+'  ·  A MOMENT, MADE BY YOU.',540,1342);x.globalAlpha=1;const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('PNG unavailable')),'image/png'));if(seq!==cardSequence)return;if(cardURL)URL.revokeObjectURL(cardURL);cardBlob=blob;cardURL=URL.createObjectURL(blob);$('#card-preview').src=cardURL;$('#save-card').disabled=false;const file=new File([blob],'paper-moon.png',{type:'image/png'});let canShare=false;try{canShare=!!navigator.canShare?.({files:[file]});}catch{}$('#share-card').hidden=!canShare;$('#share-card').disabled=false;}catch(e){toast('画像を作れませんでした。もう一度開いてください。');console.warn('PAPER MOON postcard:',e.message);}}
function openCard(){openPanel('card','この時間を、おすそわけ。','A POSTCARD FROM HERE');makeCard();}
$('#open-card').addEventListener('click',openCard);$('#brew-card').addEventListener('click',openCard);$('#message').addEventListener('input',()=>{clearTimeout(cardTimer);cardSequence++;$('#save-card').disabled=true;$('#share-card').disabled=true;cardTimer=setTimeout(makeCard,150);});
$('#save-card').addEventListener('click',()=>{if(!cardBlob)return;const a=document.createElement('a');a.href=cardURL;a.download='paper-moon-'+new Date().toISOString().slice(0,10)+'.png';document.body.append(a);a.click();a.remove();toast('ポストカードを画像にしました。');});
$('#share-card').addEventListener('click',async()=>{if(!cardBlob||!navigator.share)return;try{await navigator.share({files:[new File([cardBlob],'paper-moon.png',{type:'image/png'})],title:'PAPER MOON — 余白を、ひとくち。'});}catch(e){if(e.name!=='AbortError')toast('共有できませんでした。「画像を保存する」をお試しください。');}});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stopPour();endDrag();renderer?.pause();audio?.suspend().catch(()=>{});}else renderer?.wake();});
window.addEventListener('blur',()=>{stopPour();endDrag();});
reduced.addEventListener('change',()=>renderer?.wake());
$$('.app button').forEach(b=>b.disabled=false);if(!renderer||renderer.lost){$('#left').disabled=true;$('#right').disabled=true;}
$('#lamp').setAttribute('aria-pressed',String(state.lamp));$('.collection-dot').hidden=!state.moments.length;updateChoices();applyMood(state.mood);
// Read-only diagnostics for repeatable browser checks, not an application API.
window.PaperMoon=Object.freeze({diagnostics:()=>({renderer:renderer&&!renderer.lost?'webgl':'static',triangles:renderer?renderer.count/3:0,frames:renderer?.frames||0,animating:!!renderer?.raf,mood:state.mood,moments:state.moments.length,persistent})});
})();
