async (page) => {
 const base='http://localhost:4173/ui-lab/game-astra-solo-01/';
 const results=[],assert=(x,m)=>{if(!x)throw Error(m)};
 const go=async route=>{await page.goto(base+'?check='+Date.now()+'#'+route);await page.locator('.page-title').waitFor()};
 await go('board');
 await page.getByLabel('カテゴリ',{exact:true}).selectOption('質問');
 await page.getByRole('button',{name:'絞り込む',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('[data-thread]').length===2);
 assert(JSON.stringify((await page.locator('[data-thread]').evaluateAll(xs=>xs.map(x=>x.dataset.thread))).sort())===JSON.stringify(['t01','t03']),'questions');
 await go('board?sort=replies');
 const counts=await page.locator('.reply-count').allTextContents();
 assert(JSON.stringify(counts.map(x=>parseInt(x)))===JSON.stringify([2,2,1,1,0,0]),'reply sorting');
 results.push({id:'B01',status:'PASS',evidence:'質問=t01,t03; reply sort 2,2,1,1,0,0'});
 await page.getByRole('link',{name:'＋ スレッドを作成',exact:true}).click();
 await page.locator('#new-thread').waitFor();
 const fill=async(title,author,body)=>{await page.locator('#new-title').fill(title);await page.locator('#new-author').fill(author);await page.locator('#new-body').fill(body)};
 for(const fields of [[' ',' ',' '],['あ'.repeat(81),'テスト旅人','本文'],['題名','あ'.repeat(25),'本文'],['題名','旅人','あ'.repeat(1001)]]){
  await fill(...fields);await page.getByRole('button',{name:'確認へ進む',exact:true}).click();
  assert((await page.locator('#new-thread .error').innerText()).length>0,'invalid rejected');
  assert(await page.locator('#publish-thread').count()===0,'cannot publish invalid');
 }
 await fill('検証用：4人の編成相談','検証の旅人','支援役を入れた編成を相談します。');
 await page.getByRole('button',{name:'確認へ進む',exact:true}).click();
 await page.getByRole('button',{name:'修正する',exact:true}).click();
 assert(await page.locator('#new-title').inputValue()==='検証用：4人の編成相談','title preserved');
 assert(await page.locator('#new-author').inputValue()==='検証の旅人','author preserved');
 assert(await page.locator('#new-body').inputValue()==='支援役を入れた編成を相談します。','body preserved');
 await page.locator('#new-body').fill('支援役を先に動かす編成を相談します。');
 await page.getByRole('button',{name:'確認へ進む',exact:true}).click();
 await page.getByRole('button',{name:'この内容で投稿する',exact:true}).click();
 await page.locator('#reply-form').waitFor();
 const createdUrl=page.url();
 assert(await page.locator('.post [data-edit]').count()===1,'own parent edit available');
 await go('board');assert(await page.locator('[data-thread]').count()===7,'exactly one thread added');
 results.push({id:'B02',status:'PASS',evidence:'Blank/81 title/25 author/1001 body rejected; confirmation-revise preserves values; exactly 1 thread added',createdUrl});
 await go('thread/t01');
 assert(await page.locator('[data-edit]').count()===0,'no seed edits');
 const payload='<img src=x onerror=alert(1)>';
 let dialogs=0;const listener=async d=>{dialogs++;await d.dismiss()};page.on('dialog',listener);
 await page.locator('#reply-body').fill(payload);
 await page.getByRole('button',{name:'返信を投稿する',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#reply-count')?.textContent==='1');
 const replyId=await page.locator('.post').last().getAttribute('data-post');
 const reply=page.locator('[data-post="'+replyId+'"]');
 assert(await reply.locator('.post-body').innerText()===payload,'literal xss text');
 assert(await reply.locator('img').count()===0&&dialogs===0,'no img or alert');
 await page.reload();await page.locator('[data-post="'+replyId+'"]').waitFor();
 assert(await page.locator('[data-post="'+replyId+'"] .post-body').innerText()===payload,'xss persists literal');
 results.push({id:'B04',status:'PASS',evidence:'Literal img/onerror payload displayed, 0 img nodes, 0 JS dialogs, persisted as text'});
 await page.locator('[data-post="'+replyId+'"] [data-edit]').click();
 await page.locator('#edit-body').fill('編集後：支援役から行動します。');
 await page.locator('#modal-confirm').click();
 await page.waitForFunction(()=>document.querySelectorAll('dialog[open]').length===0);
 await page.reload();await page.locator('[data-post="'+replyId+'"] .post-body').waitFor();
 assert(await page.locator('[data-post="'+replyId+'"] .post-body').innerText()==='編集後：支援役から行動します。','edit persists');
 await page.locator('[data-post="'+replyId+'"] [data-delete]').click();
 await page.locator('#modal-cancel').click();
 assert(await page.locator('[data-post="'+replyId+'"]').count()===1,'cancel keeps reply');
 await page.locator('[data-post="'+replyId+'"] [data-delete]').click();
 await page.locator('#modal-confirm').click();
 await page.waitForFunction(()=>document.querySelector('#reply-count')?.textContent==='0');
 await page.reload();await page.locator('#reply-form').waitFor();
 assert(await page.locator('.post').count()===1,'delete persists, seed remains');
 results.push({id:'B03',status:'PASS',evidence:'Anonymous own reply added, edited, delete cancelled then confirmed; reload checks; seed has no editing action'});
 await page.locator('[data-report]').click();
 await page.locator('#report-reason').selectOption('個人情報');
 await page.locator('#modal-confirm').click();
 assert((await page.locator('#modal').innerText()).includes('理由：個人情報'),'reason confirmation');
 await page.locator('#modal-confirm').click();
 assert((await page.locator('#toast').innerText()).includes('実送信は行っていません'),'demo complete');
 assert(await page.locator('[data-post="t01"]').count()===1,'report does not delete');
 page.off('dialog',listener);
 results.push({id:'B05',status:'PASS',evidence:'Reason selected, confirmation, demo complete; original post remains; no external operation in handler'});
 return {utc:new Date().toISOString(),results};
}
