async (page) => {
  const base='http://localhost:4173/ui-lab/game-astra-solo-01/';
  const results=[];
  const assert=(x,m)=>{if(!x)throw Error(m)};
  const go=async route=>{await page.goto(base+'?check='+Date.now()+'#'+route);await page.locator('.page-title').waitFor()};
  await go('characters');
  await page.getByLabel('属性',{exact:true}).selectOption('火');
  await page.getByLabel('役割',{exact:true}).selectOption('支援');
  await page.getByRole('button',{name:'絞り込む',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-character]').length===1);
  assert(await page.locator('[data-character="c05"]').count()===1,'c05');
  await page.getByLabel('キャラ名',{exact:true}).fill('存在しない');
  await page.getByRole('button',{name:'絞り込む',exact:true}).click();
  await page.getByRole('heading',{name:'0件です'}).waitFor();
  await page.getByRole('link',{name:'リセット',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-character]').length===12);
  results.push({id:'D01',status:'PASS',evidence:'火＋支援=c05 only; unknown name=0; reset=12'});
  await page.getByLabel('並べ替え',{exact:true}).selectOption('name');
  await page.getByRole('button',{name:'絞り込む',exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll('[data-character]')[1]?.getAttribute('data-character')==='c05');
  const names=await page.locator('.character-info h3').allTextContents();
  const fixture=await page.evaluate(async()=>await (await fetch('../experiments/social-game/fixtures/content.json')).json());
  const expected=[...fixture.characters].sort((a,b)=>a.name.localeCompare(b.name,'ja')).map(c=>c.name+c.rating.toFixed(1));
  assert(JSON.stringify(names)===JSON.stringify(expected),'name order');
  await page.locator('[data-character="c01"] a').click();
  await page.getByRole('heading',{name:'アカリ',exact:true}).waitFor();
  assert((await page.locator('main').innerText()).includes('800'),'attack');
  await page.goBack();await page.locator('[data-character="c01"]').waitFor();
  await page.goForward();await page.getByRole('heading',{name:'アカリ',exact:true}).waitFor();
  await go('characters');
  const ratings=await page.locator('.rating').allTextContents();
  assert(ratings.every((x,i)=>i===0||+ratings[i-1]>=+x),'rating order');
  results.push({id:'D02',status:'PASS',evidence:'Name and rating order match fixture; c01 attack=800; back/forward work'});
  await page.getByLabel('サイト内検索',{exact:true}).fill('結晶');
  await page.getByRole('button',{name:'検索する',exact:true}).click();
  await page.getByRole('heading',{name:'サイト内検索',exact:true}).waitFor();
  assert(await page.locator('main .guide-row').count()===26,'26 search results');
  await page.getByLabel('検索語',{exact:true}).fill('存在しない');
  await page.locator('main').getByRole('button',{name:'検索する',exact:true}).click();
  await page.getByRole('heading',{name:'0件です'}).waitFor();
  results.push({id:'S01',status:'PASS',evidence:'結晶=26 (12 characters+8 guides+6 threads), missing query=0'});
  await go('guide/g01');
  const bm=page.locator('[data-bookmark="g01"]');
  if(await bm.getAttribute('aria-pressed')==='true')await bm.click();
  await bm.click();await bm.click();await bm.click();await page.reload();
  await page.locator('[data-bookmark="g01"][aria-pressed="true"]').waitFor();
  assert(await page.locator('.article section').count()===4,'3 sections+related');
  await go('saved');assert(await page.locator('[data-guide="g01"]').count()===1,'bookmark list');
  results.push({id:'A01',status:'PASS',evidence:'save/remove/resave/reload; saved list has g01; 3 body sections+related'});
  return {utc:new Date().toISOString(),browser:page.context().browser()?.version(),results};
}
